import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Link from "next/link";

export default function Cart({ }) {
    return (
        <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">

            <Head>
                <title>Cart</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>

            <div className="container">
                <div className="w-full max-w-[640px] mx-auto mb-8">
                    <div className="w-full bg-white mb-1.5">
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    );
}

