import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Footer from '../../components/footer'
import SlidePage from '../../components/modules/slide-page';
import SliderNhomSanPham from '../../components/modules/slider-nhom-san-pham';
import SliderSanPham from '../../components/modules/slider-san-pham';
import Link from 'next/link'


export default function ListProducts({ }) {
  return (
    <div id="main" className="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
      <Head>
        <title>Hot products</title>
        <meta name="description" content="Generated by Huy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="container">
        <div className="lg:pl-60 w-full xs:pt-2">
          <div className="sm:mb-4">
            <div className="hidden xs:block">
              <SlidePage />
            </div>
            <div class={`overflow-hidden mb-4 mt-4 sm:mb-6 lg:mb-7 ${styles.limit_text_1}`}>
              <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Trang chủ</a>
              <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Sản phẩm</a>
              <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Khuyến mãi hot</a>
            </div>
            <SliderSanPham />
            <SliderSanPham />
            <SliderSanPham />
            <SliderNhomSanPham />
            <SliderNhomSanPham />
            <SliderNhomSanPham />
          </div>
          <Footer />
        </div>
      </div>
    </div>
  )
}