import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import BoxComments from '../../components/modules/box-comments';
import Link from "next/link";

export default function Introduce({ }) {
    return (
        <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>Introduce</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>
            <div className="sm:container">
                <div className="bg-white mb-8">
                    <div className="w-full bg-white px-4 sm:px-5 inline-block">
                        <div className="max-w-2xl mx-auto my-5 xs:my-11">
                            <div className="w-full mb-8">
                                <img src="./images/Introduce.png" alt="" className="w-full object-cover" />
                            </div>
                            <div className="w-full mb-8 flex items-start justify-between p-2 xs:p-3 sm:p-4 border border-red-500 rounded overflow-hidden bg-white shadow-3xl">
                                <div className="w-1/3 grid gap-2 items-center justify-center border-r border-gray-300 last:border-none p-2">
                                    <h2 className="text-xl xs:text-2xl sm:text-3xl text-red-500 font-bold text-center">10.000+</h2>
                                    <p className="text-xs xs:text-sm text-texth text-center">Nhân viên</p>
                                </div>
                                <div className="w-1/3 grid gap-2 items-center justify-center border-r border-gray-300 last:border-none p-2">
                                    <h2 className="text-xl xs:text-2xl sm:text-3xl text-red-500 font-bold text-center">6</h2>
                                    <p className="text-xs xs:text-sm text-texth text-center">Năm thành lập</p>
                                </div>
                                <div className="w-1/3 grid gap-2 items-center justify-center border-r border-gray-300 last:border-none p-2">
                                    <h2 className="text-xl xs:text-2xl sm:text-3xl text-red-500 font-bold text-center">1.900+</h2>
                                    <p className="text-xs xs:text-sm text-texth text-center">Cửa hàng</p>
                                </div>
                            </div>
                            <div className="mb-11">
                                <h2 className="text-2xl text-black mb-3 font-medium text-center">Giới thiệu về T-Mart</h2>
                                <p className="text-base text-texth mb-3">
                                    Chúng tôi mong muốn mang đến sự nhanh chóng và tiện lợi tối đa khi mua sắm đến cho khách hàng bằng việc đưa hệ thống siêu thị <a href="" title="" className="text-base text-red-500">T-Mart</a> phủ rộng khắp mọi khu vực kể cả vùng nông thôn. Bên cạnh đó, chúng tôi cũng tập trung phát triển kênh mua sắm online trên website <a href="" title="" className="text-base text-red-500">tmart.com</a> để phục vụ cho mọi đối tượng, đặc biệt là nhóm khách hàng trẻ.
                                </p>
                                <p className="text-base text-texth mb-3"><a href="" title="" className="text-base text-red-500">T-Mart</a> cũng không ngừng tìm kiếm và mang đến sự đa dạng trong việc lựa chọn sản phẩm với hơn 12.000 sản phẩm đủ chủng loại, xuất xứ rõ ràng, giá cả hợp lý, minh bạch.</p>
                            </div>
                            <button
                                className="w-full h-12 xs:h-14 sm:h-[60px] overflow-hidden bg-color1 border border-color1 text-white leading-[0] rounded-full flex items-center justify-center relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-white before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-color1">
                                <span className="text-sm xs:text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-[100%] z-[2]">
                                    CÁC CỘT MỐC CỦA T-MART
                                </span>
                            </button>
                            <div className="my-10 xs:my-14">
                                <ul className="w-fit mx-auto">
                                    <li class="group last:pb-0 last:after:hidden relative flex pb-8 sm:pb-11 cursor-pointer before:content-[attr(before)] before:bg-green-600 before:min-w-[8px] before:h-[8px] xs:before:min-w-[10.77px] xs:before:h-[10.77px] before:mx-7 sm:before:mx-10 before:mt-1 before:rounded-full before:order-2 before:transform before:-translate-x-1/2 after:content-[attr(after)] before:z-10 after:absolute after:top-[10px] after:left-[97.5px] sm:after:left-[109.5px] after:z-[1] after:bg-green-600 after:w-[1px] after:h-full hover:before:bg-white hover:before:mt-[2px] hover:before:min-w-[12px] hover:before:h-[12px] hover:before:border-2 xs:hover:before:min-w-[19.39px] xs:hover:before:h-[19.39px] xs:hover:before:border-4 hover:before:border-green-600">
                                        <div class={`text-right order-1 min-w-[70px] group-hover:font-bold overflow-hidden group-hover:text-green-600 text-xs xs:text-sm ${styles.limit_text_1}`}>2016</div>
                                        <div class={`order-3 overflow-hidden text-xs xs:text-sm ${styles.limit_text_3}`}>Thành lập Công ty Cổ phần T-Mart</div>
                                    </li>
                                    <li class="group last:pb-0 last:after:hidden relative flex pb-8 sm:pb-11 cursor-pointer before:content-[attr(before)] before:bg-green-600 before:min-w-[8px] before:h-[8px] xs:before:min-w-[10.77px] xs:before:h-[10.77px] before:mx-7 sm:before:mx-10 before:mt-1 before:rounded-full before:order-2 before:transform before:-translate-x-1/2 after:content-[attr(after)] before:z-10 after:absolute after:top-[10px] after:left-[97.5px] sm:after:left-[109.5px] after:z-[1] after:bg-green-600 after:w-[1px] after:h-full hover:before:bg-white hover:before:mt-[2px] hover:before:min-w-[12px] hover:before:h-[12px] hover:before:border-2 xs:hover:before:min-w-[19.39px] xs:hover:before:h-[19.39px] xs:hover:before:border-4 hover:before:border-green-600">
                                        <div class={`text-right order-1 min-w-[70px] group-hover:font-bold overflow-hidden group-hover:text-green-600 text-xs xs:text-sm ${styles.limit_text_1}`}>2017</div>
                                        <div class={`order-3 overflow-hidden text-xs xs:text-sm ${styles.limit_text_3}`}>Thành lập Công ty Cổ phần T-Mart</div>
                                    </li>
                                    <li class="group last:pb-0 last:after:hidden relative flex pb-8 sm:pb-11 cursor-pointer before:content-[attr(before)] before:bg-green-600 before:min-w-[8px] before:h-[8px] xs:before:min-w-[10.77px] xs:before:h-[10.77px] before:mx-7 sm:before:mx-10 before:mt-1 before:rounded-full before:order-2 before:transform before:-translate-x-1/2 after:content-[attr(after)] before:z-10 after:absolute after:top-[10px] after:left-[97.5px] sm:after:left-[109.5px] after:z-[1] after:bg-green-600 after:w-[1px] after:h-full hover:before:bg-white hover:before:mt-[2px] hover:before:min-w-[12px] hover:before:h-[12px] hover:before:border-2 xs:hover:before:min-w-[19.39px] xs:hover:before:h-[19.39px] xs:hover:before:border-4 hover:before:border-green-600">
                                        <div class={`text-right order-1 min-w-[70px] group-hover:font-bold overflow-hidden group-hover:text-green-600 text-xs xs:text-sm ${styles.limit_text_1}`}>06/2018</div>
                                        <div class={`order-3 overflow-hidden text-xs xs:text-sm ${styles.limit_text_3}`}>Thành lập Công ty Cổ phần T-Mart</div>
                                    </li>
                                    <li class="group last:pb-0 last:after:hidden relative flex pb-8 sm:pb-11 cursor-pointer before:content-[attr(before)] before:bg-green-600 before:min-w-[8px] before:h-[8px] xs:before:min-w-[10.77px] xs:before:h-[10.77px] before:mx-7 sm:before:mx-10 before:mt-1 before:rounded-full before:order-2 before:transform before:-translate-x-1/2 after:content-[attr(after)] before:z-10 after:absolute after:top-[10px] after:left-[97.5px] sm:after:left-[109.5px] after:z-[1] after:bg-green-600 after:w-[1px] after:h-full hover:before:bg-white hover:before:mt-[2px] hover:before:min-w-[12px] hover:before:h-[12px] hover:before:border-2 xs:hover:before:min-w-[19.39px] xs:hover:before:h-[19.39px] xs:hover:before:border-4 hover:before:border-green-600">
                                        <div class={`text-right order-1 min-w-[70px] group-hover:font-bold overflow-hidden group-hover:text-green-600 text-xs xs:text-sm ${styles.limit_text_1}`}>25/10/20</div>
                                        <div class={`order-3 overflow-hidden text-xs xs:text-sm ${styles.limit_text_3}`}>Thành lập Công ty Cổ phần T-Mart</div>
                                    </li>
                                    <li class="group last:pb-0 last:after:hidden relative flex pb-8 sm:pb-11 cursor-pointer before:content-[attr(before)] before:bg-green-600 before:min-w-[8px] before:h-[8px] xs:before:min-w-[10.77px] xs:before:h-[10.77px] before:mx-7 sm:before:mx-10 before:mt-1 before:rounded-full before:order-2 before:transform before:-translate-x-1/2 after:content-[attr(after)] before:z-10 after:absolute after:top-[10px] after:left-[97.5px] sm:after:left-[109.5px] after:z-[1] after:bg-green-600 after:w-[1px] after:h-full hover:before:bg-white hover:before:mt-[2px] hover:before:min-w-[12px] hover:before:h-[12px] hover:before:border-2 xs:hover:before:min-w-[19.39px] xs:hover:before:h-[19.39px] xs:hover:before:border-4 hover:before:border-green-600">
                                        <div class={`text-right order-1 min-w-[70px] group-hover:font-bold overflow-hidden group-hover:text-green-600 text-xs xs:text-sm ${styles.limit_text_1}`}>30/06/21</div>
                                        <div class={`order-3 overflow-hidden text-xs xs:text-sm ${styles.limit_text_3}`}>Thành lập Công ty Cổ phần T-Mart</div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div className={`w-full py-10 px-4 sm:px-5 ${styles.bg_li_blue}`}>
                        <div className="max-w-5xl mx-auto mb-10 sm:mb-16">
                            <div className="flex flex-wrap sm:px-10 lg:px-0 lg:flex-nowrap gap-8 md:gap-10 lg:gap-14 xl:gap-28">
                                <div className="w-full lg:w-1/2">
                                    <h2 className="mb-5 xs:mb-8 text-xl xs:text-2xl font-bold text-green-600 text-center">Khách hàng nói gì về T-MART</h2>
                                    <div className="w-full p-5 bg-white overflow-hidden rounded mb-4">
                                        <h3 className="text-black text-base font-medium text-center mb-4">Chị Phan Phụng</h3>
                                        <p className="text-texth text-sm">"Nhân viên giữ xe cũng rất là lịch sự. Hàng khuyến mãi đều đặn, giá rẻ, chất lượng tốt."</p>
                                    </div>
                                    <div className="w-full p-5 bg-white overflow-hidden rounded mb-4">
                                        <h3 className="text-black text-base font-medium text-center mb-4">Chị Phan Phụng</h3>
                                        <p className="text-texth text-sm">"Nhân viên giữ xe cũng rất là lịch sự. Hàng khuyến mãi đều đặn, giá rẻ, chất lượng tốt."</p>
                                    </div>
                                </div>
                                <div className="w-full lg:w-1/2">
                                    <h2 className="mb-5 xs:mb-8 text-xl xs:text-2xl font-bold text-green-600 text-center">Báo chí truyền thông nói gì về T-MART</h2>
                                    <p className="text-texth text-sm mb-3"><b>Thanhnien.vn</b></p>
                                    <p className="text-texth text-sm mb-3">"Ở những vùng quê, người dân vốn chỉ quen với thịt cá, trái cây địa phương giờ đây có thể tìm thấy thêm những lựa chọn thực phẩm ngoại nhập chất lượng cao mà giá cả lại vừa túi tiền."</p>
                                    <p className="text-texth text-sm mb-3"><b>Tuoitre.vn</b></p>
                                    <p className="text-texth text-sm mb-3">"Khó mà tưởng tượng một siêu thị chỉ vài trăm mét vuông nhưng có tới hàng chục loại hải sản: cua, ghẹ, nghêu, tôm sống, cá hồi, cá bớp, cá biển và các loại cá nhập khẩu, rau củ đầy đủ..."</p>
                                    <p className="text-texth text-sm mb-3">"Những khách hàng lớn tuổi vốn không quen mua sắm online vẫn có thể dễ dàng thao tác bởi các thiết kế tối ưu giúp khách hàng dễ tìm món hàng, thao tác mua bán ngắn gọn và thuận tiện."</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sm:container">
                <div className="bg-white p-4 sm:p-5 mb-7">
                    <BoxComments />
                </div>
            </div>
            <div className="container">
                <Footer />
            </div>
        </div>
    );
}

