import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Footer from '../../components/footer'
import SlidePage from '../../components/modules/slide-page';
import ProductItem from "../../components/layouts/product/product-item";
import Link from 'next/link'


export default function ListProducts({ }) {
  var prds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];
  return (
    <div id="main" className="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
      <Head>
        <title>List products</title>
        <meta name="description" content="Generated by Huy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="container">
        <div className="lg:pl-60 w-full xs:pt-2">
          <div className="sm:mb-4">
            <div className="hidden xs:block">
              <SlidePage />
            </div>
            <div class={`overflow-hidden mb-4 mt-4 sm:mb-6 lg:mb-7 ${styles.limit_text_1}`}>
              <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Trang chủ</a>
              <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Sản phẩm</a>
              <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Hoa quả</a>
            </div>
          </div>
          <div className=" mb-8" id="">
            <div className="sm:h-14 bg-white z-10 px-2 xs:px-4 sm:mb-3 relative overflow-hidden before:content-[attr(before)] before:w-full before:h-[2px] before:bg-red-600 before:absolute before:top-[12px] before:left-0 sm:before:hidden">
              <div className="sm:h-14 sm:leading-14 w-full sm:w-auto flex items-center flex-wrap float-left">
                <div className='w-full sm:w-auto '>
                  <div
                    className="flex items-center justify-between relative w-fit mx-auto mb-3 z-10 px-8 xs:px-12 py-2 sm:bolck sm:m-0 sm:p-0">
                    <div className="w-8 h-8 sm:hidden">
                      <img src="./images/icon/set.png" alt="" className="min-w-[30px] w-full" />
                    </div>
                    <h2 className="text-base text-white sm:text-gray-800 text-center md:text-left font-medium uppercase sm:mr-1 xl:mr-4">Rau, củ, trái cây</h2>
                    <div className="w-8 h-8 sm:hidden">
                      <img src="./images/icon/set1.png" alt="" className="min-w-[30px] w-full" />
                    </div>
                    <div className="w-full h-full absolute top-0 left-1/2 -translate-x-1/2 overflow-auto -z-10 sm:hidden">
                      <img src="./images/bg-title.png" alt="" className="w-full h-full" />
                    </div>
                  </div>
                </div>
              </div>
              <div before="" className="sm:h-14 sm:leading-14 flex items-center mb-3 sm:mb-0 float-left z-[1]before:content-[attr(before)] before:w-px before:h-4 before:bg-gray-400 before:mx-3 before:order-3 before:hidden sm:before:block">
                <div className="text-blue-500 text-xs order-2 hidden xl:block">
                  Táo
                  Cam, bưởi
                  Lê
                  Xoài
                  Chuối
                  Khác (Dưa, ổi, bơ,...)
                </div>
                <select name="" id="" className="bg-transparent	text-blue-500 text-xs pr-2 order-4">
                  <option value="">Nhóm trái cây</option>
                  <option value="">Táo</option>
                  <option value="">Cam</option>
                  <option value="">Xoài</option>
                  <option value="">Chuối</option>
                </select>
              </div>
              <div className="mb-5 sm:mb-0 sm:h-14 sm:leading-14 flex items-center float-right">
                  <select name="" id="" className="h-8 leading-8 border border-gray-400 rounded bg-transparent xs:p-1	text-blue-600 text-xs xs:text-[13px] pr-2">
                    <option value="">Sản phẩm liên quan</option>
                    <option value="">Táo</option>
                    <option value="">Cam</option>
                    <option value="">Xoài</option>
                    <option value="">Chuối</option>
                  </select>
                </div>
            </div>
            <div className="">
              <div className="bg-white mb-5">
                <div className="w-full grid gap-[1px] grid-cols-2 xs:grid-cols-3 xl:grid-cols-4 bg-gray-300">
                  {
                    prds.map((item, index) => (
                      <ProductItem />
                    ))
                  }
                </div>
              </div>
              <div class={`text-texth relative max-h-96 overflow-hidden bg-white p-4 xs:p-5 sm:p-8 ${styles.products_description}`}>
                <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng Đệm lunarlon
                  mềm và vững chắc Cấu trúc form giày Flywire Công nghệ Flymesh siêu nhẹ và thoáng khí Cấu
                  trúc lưới nhẹ, đa lớp sử dụng vật liệu lót tối thiểu để giảm độ cứng gót chân</p>
                <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                  thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                  người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>
                <p>Đệm lunarlon mềm và vững chắc.</p>
                <p>Cấu trúc form giày Flywire.</p>
                <p>Công nghệ Flymesh siêu nhẹ và thoáng khí.</p>
                <p>Cấu trúc lưới nhẹ, đa lớp sử dụng vật liệu lót tối thiểu để giảm độ
                  cứng gót chân.</p>
                <p>Logo Nike được bố trí nổi bật trên sản phẩm kết hợp màu sắc ấn
                  tượng, phong cách hiện đại sẽ góp phần khẳng định phong cách thời trang của bạn.
                </p>
                <p>Nike là nhà cung cấp trang phục và dụng cụ thể thao thương mại công
                  cộng hàng đầu trên thế giới, có trụ sở tại Hoa Kỳ. Cho đến nay, các sản phẩm của
                  Nike đang được hàng loạt vận động viên xuất sắc, những người nổi tiếng tin tưởng và
                  lựa chọn.</p>
                <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                  thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                  người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>
                <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                  thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                  người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>
                <p>Đệm lunarlon mềm và vững chắc.</p>
                <p>Cấu trúc form giày Flywire.</p>
                <p>Công nghệ Flymesh siêu nhẹ và thoáng khí.</p>
                <p>Cấu trúc lưới nhẹ, đa lớp sử dụng vật liệu lót tối thiểu để giảm độ
                  cứng gót chân.</p>
                <p>Logo Nike được bố trí nổi bật trên sản phẩm kết hợp màu sắc ấn
                  tượng, phong cách hiện đại sẽ góp phần khẳng định phong cách thời trang của bạn.
                </p>
                <p>Nike là nhà cung cấp trang phục và dụng cụ thể thao thương mại công
                  cộng hàng đầu trên thế giới, có trụ sở tại Hoa Kỳ. Cho đến nay, các sản phẩm của
                  Nike đang được hàng loạt vận động viên xuất sắc, những người nổi tiếng tin tưởng và
                  lựa chọn.</p>
                <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                  thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                  người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>

                <div class={`absolute bottom-0 left-0 w-full h-48 flex items-end justify-center pb-4 ${styles.click_more}`}>
                  <button id="btn-more" className="flex items-center justify-center">
                    <span className="text-[13px] text-green-500 font-medium">Xem thêm</span>
                    <svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                      xmlns="http://www.w3.org/2000/svg" className="ml-1 mt-1">
                      <path d="M9.09742 12.1336L8.15409 11.1916L11.2208 8.12491L8.15409 5.05824L9.09742 4.12024L13.1041 8.12691L9.09809 12.1336H9.09742ZM5.48075 12.1336L4.53809 11.1916L7.60475 8.12491L4.53809 5.06291L5.48075 4.12024L9.48809 8.12691L5.48142 12.1336H5.48075Z"
                        fill="#00A652" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <Footer />
        </div>
      </div>
    </div>
  )
}