import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Link from "next/link";

export default function Account({ }) {
  return (
    <div id="main" className="overflow-hidden bg-gray-100 pb-20 xs:pb-0">

      <Head>
        <title>Tai khoan 1</title>
        <meta name="description" content="Generated by Huy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden shadow">
        <Header />
      </div>

      <div className="sm:container">
        <div className="w-full max-w-4xl mx-auto mb-8">
          <div className="w-full bg-white p-4 xs:p-8 mb-3">
            <div className="mb-3 xs:mb-5">
              <h2 className="text-base xs:text-lg text-black font-medium mb-2">
                Nguyễn Văn A
              </h2>
              <p className="text-sm sm:text-base">Điểm của tôi: <span className="">175 điểm</span></p>
            </div>
            <div className="flex items-center gap-3 justify-between">
              <Link href={'/account-information'}>
                <a className="group flex items-center zoom-80 xs:zoom-100" href="" title="">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="currentColor" className="text-blue-500 mr-2 group-hover:text-red-500">
                    <path fillRule="evenodd" clipRule="evenodd"
                      d="M7.33301 13.3334C7.33301 12.9652 7.63148 12.6667 7.99967 12.6667H13.9997C14.3679 12.6667 14.6663 12.9652 14.6663 13.3334C14.6663 13.7016 14.3679 14.0001 13.9997 14.0001H7.99967C7.63148 14.0001 7.33301 13.7016 7.33301 13.3334Z"
                      fill="" />
                    <path fillRule="evenodd" clipRule="evenodd"
                      d="M11.9997 2.58577C11.8014 2.58577 11.6113 2.66453 11.4711 2.80473L3.26833 11.0075L2.91593 12.4171L4.32552 12.0647L12.5283 3.86192C12.5977 3.7925 12.6528 3.71009 12.6903 3.6194C12.7279 3.5287 12.7472 3.43149 12.7472 3.33332C12.7472 3.23515 12.7279 3.13794 12.6903 3.04725C12.6528 2.95655 12.5977 2.87414 12.5283 2.80473C12.4589 2.73531 12.3765 2.68025 12.2858 2.64268C12.1951 2.60511 12.0979 2.58577 11.9997 2.58577ZM10.5283 1.86192C10.9185 1.47168 11.4478 1.25244 11.9997 1.25244C12.273 1.25244 12.5435 1.30626 12.796 1.41084C13.0485 1.51541 13.2779 1.66869 13.4711 1.86192C13.6643 2.05514 13.8176 2.28454 13.9222 2.537C14.0267 2.78947 14.0806 3.06006 14.0806 3.33332C14.0806 3.60659 14.0267 3.87718 13.9222 4.12964C13.8176 4.3821 13.6643 4.6115 13.4711 4.80473L5.13776 13.1381C5.05232 13.2235 4.94527 13.2841 4.82805 13.3134L2.16138 13.9801C1.9342 14.0369 1.69387 13.9703 1.52828 13.8047C1.3627 13.6391 1.29613 13.3988 1.35293 13.1716L2.01959 10.505C2.0489 10.3877 2.10951 10.2807 2.19495 10.1953L10.5283 1.86192Z"
                      fill="" />
                  </svg>
                  <span className="text-blue-500 group-hover:text-red-500">Sửa thông tin</span>
                </a>
              </Link>
              <a className="group flex items-center zoom-80 xs:zoom-100" href="" title="">
                <svg width="18" height="18" viewBox="0 0 18 18" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className="text-blue-500 mr-2 group-hover:text-red-500">
                  <path fillRule="evenodd" clipRule="evenodd" d="M10.5 15.75C10.5 15.3358 10.8358 15 11.25 15L14.25 15C14.4489 15 14.6397 14.921 14.7803 14.7803C14.921 14.6397 15 14.4489 15 14.25L15 3.75C15 3.55109 14.921 3.36032 14.7803 3.21967C14.6397 3.07902 14.4489 3 14.25 3L11.25 3C10.8358 3 10.5 2.66421 10.5 2.25C10.5 1.83579 10.8358 1.5 11.25 1.5L14.25 1.5C14.8467 1.5 15.419 1.73705 15.841 2.15901C16.2629 2.58096 16.5 3.15326 16.5 3.75L16.5 14.25C16.5 14.8467 16.2629 15.419 15.841 15.841C15.419 16.2629 14.8467 16.5 14.25 16.5L11.25 16.5C10.8358 16.5 10.5 16.1642 10.5 15.75Z" fill="" />
                  <path fillRule="evenodd" clipRule="evenodd" d="M6.96967 13.2803C6.67678 12.9874 6.67678 12.5126 6.96967 12.2197L10.1893 9L6.96967 5.78033C6.67678 5.48744 6.67678 5.01256 6.96967 4.71967C7.26256 4.42678 7.73744 4.42678 8.03033 4.71967L11.7803 8.46967C12.0732 8.76256 12.0732 9.23744 11.7803 9.53033L8.03033 13.2803C7.73744 13.5732 7.26256 13.5732 6.96967 13.2803Z" fill="" />
                  <path fillRule="evenodd" clipRule="evenodd" d="M1.5 9C1.5 8.58579 1.83579 8.25 2.25 8.25L11.25 8.25C11.6642 8.25 12 8.58579 12 9C12 9.41421 11.6642 9.75 11.25 9.75L2.25 9.75C1.83579 9.75 1.5 9.41421 1.5 9Z" fill="" />
                </svg>
                <span className="text-blue-500 group-hover:text-red-500">Thoát tài khoản</span>
              </a>
            </div>
          </div>
          <div className="w-full bg-white px-4 mb-3">
            <div className="flex items-center gap-8 xs:gap-10 sm:gap-20">
              <a className={`group py-3 relative before:hidden before:content-[attr(before)] before:absolute before:w-10/12 before:h-[3px] before:bg-red-500 before:bottom-0 before:left-1/2 before:-translate-x-1/2 flex items-center hover:before:block ${styles.lider}`} href="" title="">
                <span className="text-sm xs:text-base text-gray-500 group-hover:text-black group-hover:font-medium">Lịch sử mua hàng</span>
              </a>
              <a className={`group py-3 relative before:hidden before:content-[attr(before)] before:absolute before:w-10/12 before:h-[3px] before:bg-red-500 before:bottom-0 before:left-1/2 before:-translate-x-1/2 flex items-center hover:before:block`} href="" title="">
                <span className="text-sm xs:text-base text-gray-500 group-hover:text-black group-hover:font-medium">Phiếu mua hàng</span>
              </a>
            </div>
          </div>
          {/* <div className="w-full bg-white px-8 sm:px-11 py-8 mb-3 overflow-hidden">
            <div className="my-20">
              <img src="./images/fall.png" alt="" className="mx-auto" />
            </div>
            <button
              className="w-full p-3 xs:p-4 overflow-hidden bg-color1 border border-color1 text-white leading-[0] rounded flex items-center justify-center relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-white before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-color1">
              <span className="text-sm xs:text-base font-medium leading-[100%] z-[2]">
                Mua sắm ngay
              </span>
            </button>
          </div> */}
          <form id="" className="">
            <div className="w-full bg-white p-4 mb-3 overflow-hidden">
              <div className="flex items-center justify-between mb-3">
                <label className="text-sm"><b>ĐH #64785588</b></label>
                <label class="flex items-center text-sm text-color1">
                  <div className="bg-color1 p-[3px] rounded-full overflow-hidden mr-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="9" height="9" fill="currentColor" class="bi bi-cart4 text-white" viewBox="0 0 16 16">
                      <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
                    </svg>
                  </div>
                  Chờ xuất hàng
                  <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chevron-down ml-4" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                  </svg>
                </label>
              </div>
              <div className="">
                <div className="flex items-center text-sm mb-3">
                  <img src="./images/icon/$$$.png" alt="" className="mr-1" width={16} />
                  Thanh toán khi nhận hàng
                  <div className="flex items-center text-sm text-blue-500 ml-4">
                    Xem thêm
                    <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chevron-down ml-1" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                    </svg>
                  </div>
                </div>


                <ul className="text-xs mb-5 hidden">
                  <li className="mb-2">
                    <div className="flex items-center gap-1 text-sm text-black">
                      <span className="text-bdtext">Người nhận: </span>
                      <span className="font-medium" id="gender">Anh</span>
                      <span className="font-medium" id="name"> Dasssss</span>
                      <span className="font-medium" id="phone">(0925487121)</span>
                      <a href="" title="" className="font-normal text-blue-500">
                        Đổi
                      </a>
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-sm text-black">
                      <span className="text-bdtext">Địa chỉ giao: </span>
                      <span className="font-medium">123, Phường An Khánh (Q2), TP. Thủ Đức (Q2, Q9, Thủ Đức), TP. Hồ Chí Minh</span>
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-sm text-color1">
                      <a className="addnote" onclick="">Thêm ghi chú</a>
                    </div>
                  </li>
                </ul>
                <ul className="text-xs mb-5 ">
                  <li className="mb-2">
                    <div className="text-sm text-black">
                      <span className="text-bdtext mr-5">Giao lúc: </span>
                      Trước 14:00 30/12 <a href="" title="" className="font-normal text-blue-500">(Đổi thời gian giao)</a>
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-sm text-black">
                      Điểm tích luỹ tạm tính: 4.190 điểm (4.190₫)
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-xs text-black">
                      <a className="" href="" title="">Xem hướng dẫn tích và sử dụng điểm</a>
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-xs text-black">
                      Yêu cầu đồng kiểm tra sản phẩm khi nhận hàng
                    </div>
                  </li>
                </ul>
                <div className="zoom-80 xs:zoom-100 border-t " data-type="">
                  <div className="text-black">
                    <div className="">
                      <div className="">
                        <div className="border-b py-2">
                          <div className="flex gap-3 justify-between">
                            <div className="flex gap-3">
                              <img alt="Dầu xả Pantene 3MM Biotin ngăn rụng tóc 480ml" src="https://cdn.tgdd.vn/Products/Images/2484/291966/bhx/dau-xa-pantene-3mm-biotin-ngan-rung-toc-480ml-202210110910224605_300x300.jpg" width="60" height="60" />
                              <div className="">
                                <div className="mb-2">
                                  <a className="text-sm" href="">
                                    Dầu xả Pantene 3MM Biotin ngăn rụng tóc 480ml
                                  </a>
                                </div>
                                <div className="text-xs text-blurtext mb-1">
                                  <label>Số lượng:</label>
                                  <span className="text">
                                    1
                                  </span>
                                </div>
                                <div className="text-xs text-blurtext mb-1 flex items-center">
                                  <svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" viewBox="0 0 82.14 122.88" width="14" height="14" fill="currentColor" className="text-blurtext mr-1"><g><path d="M75,80.53c1.09-11.23-0.67-21.99-7.36-34.73c-1.37,8.96-4.51,14.01-11.31,20.53c-2.97-17.65-12.67-34.14-21.9-49.42 c0.54,20.29-6.07,49.28-19.71,64.91c-1.67-8.15-0.47-12.35-1.55-20.57c-1.83,7.34-5.64,11.96-6.69,22.07 c-0.85,8.25,1.47,15.26,5.77,20.64c4.8,6,12.08,10.05,20.23,11.63C56.08,120.16,72.75,103.65,75,80.53L75,80.53z M59.64,117.53 c-4.74,3.09-9.29,4.64-14,5.15c-4.59,0.5-9.23,0.01-14.32-0.97c-9.56-1.85-18.16-6.68-23.91-13.87 c-18.06-22.57,2.36-46.03,3.81-71.92c6.31,7.7,6.95,12.2,8.09,22.31c0.12,1.07,0.22,2.14,0.3,3.21c2.61-6.6,4.57-13.56,5.93-20.43 c2.97-15,3.13-26.27,0.18-41.01c10.94,6.6,16.63,15.28,22.86,26.61c3.84,7,7.52,14.32,10.81,23.37c2.35-9.32,2.9-12.34,0.47-22.3 C88.44,45.72,90.75,97.2,59.64,117.53L59.64,117.53z" /></g></svg>
                                  Giảm 39% chai thứ 2
                                </div>
                              </div>
                            </div>
                            <div className="text-xs">
                              <div className="mb-1">
                                <strong>164.000₫</strong>
                              </div>
                              <div className="line-through text-blurtext">
                                <span><b>186.000₫</b></span>
                              </div>
                            </div>
                          </div>
                          <div className="clr"></div>
                        </div>
                      </div>
                      <div className="border-b-[3px] py-2 text-sm">
                        <div className="flex items-center justify-end mb-2">
                          <span className="text-blurtext">Tiền hàng:</span>
                          <label className="text-cltext w-32 text-right">164.000₫</label>
                        </div>
                        <div className="flex items-center justify-end">
                          <span className="text-blurtext">Phí giao:</span>
                          <label className="text-cltext w-32 text-right">15.000₫</label>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="py-2 text-sm">
                    <div className="flex items-center justify-end mb-2">
                      <span className="text-blurtext">Tiền hàng:</span>
                      <label className="text-cltext w-32 text-right">164.000₫</label>
                    </div>
                    <div className="">
                      <div className="flex items-center justify-end mb-2">
                        <span className="text-blurtext">Phí giao hàng</span>
                        <label className="text-cltext w-32 text-right">
                          15.000₫
                        </label>
                      </div>
                    </div>
                    <div className="">
                      <div className="flex items-center justify-end mb-2">
                        <span className="text-blurtext">Tổng tiền: </span>
                        <label className="text-cltext w-32 text-right">
                          <b>179.000₫</b>
                        </label>
                      </div>
                    </div>
                    <div className="flex items-center justify-end pt-2">
                      <a onclick="" className="w-fit h-8 px-2 flex items-center justify-center rounded border-blue-500 border overflow-hidden mb-5">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" fill="currentColor" className="text-blue-500 mr-1" id="Layer_1" data-name="Layer 1" viewBox="0 0 112.68 122.88"><path d="M100.87,60.09c-5.65-8.65-9.59-14.76-13.78-21.23-2.2-3.41-4.48-6.93-7.44-11.48l-1.3.85a2.7,2.7,0,0,1-4-3.12,2.64,2.64,0,0,1,1.08-1.4l1.31-.86c-3-4.68-6.77-10.39-11.59-17.77a.68.68,0,0,0-.41-.28.71.71,0,0,0-.49.09L62,6.32a10.12,10.12,0,0,1,.45,5.75,10.24,10.24,0,0,1-4.36,6.44l-.07.06A10.31,10.31,0,0,1,45.34,17.4L43,18.86a10.3,10.3,0,0,1,.48,5.56A10.13,10.13,0,0,1,39.09,31l-.37.24a10.09,10.09,0,0,1-7.58,1.28,10.39,10.39,0,0,1-5-2.71l-2.93,1.91a.65.65,0,0,0-.24.38.68.68,0,0,0,0,.42l.1.16c4.7,7.19,8.39,12.93,11.47,17.72l.08,0,4.52-3a2.7,2.7,0,0,1,4,3.12,2.74,2.74,0,0,1-1.08,1.4l-4.52,2.95-.12.07c1.13,1.77,2.22,3.46,3.35,5.19Zm-65.68,0-3.85-6c-3.1-4.83-6.85-10.67-12.25-18.94h0a5.43,5.43,0,0,1,1.55-7.5c1.26-.84,3.49-2.47,4.74-3.1a2.4,2.4,0,0,1,3.31.73l0,.06a5.61,5.61,0,0,0,3.46,2.46,5.36,5.36,0,0,0,4-.67l.25-.16a5.37,5.37,0,0,0,2.31-3.46,5.6,5.6,0,0,0-.86-4.15l-.09-.15a2.4,2.4,0,0,1,.79-3.29l5.95-3.65a2.39,2.39,0,0,1,3.32.69,5.45,5.45,0,0,0,7.57,1.59l.06,0a5.5,5.5,0,0,0,2.32-3.43,5.34,5.34,0,0,0-.76-4l-.15-.22a2.4,2.4,0,0,1,.7-3.32l4-2.62a5.45,5.45,0,0,1,7.52,1.58C80,19,85.73,28,91.11,36.26c4,6.26,7.83,12.11,15.49,23.83h.63a5.46,5.46,0,0,1,5.45,5.44v5.61a2.41,2.41,0,0,1-2.4,2.4H110a5.3,5.3,0,0,0-3.77,1.57,5.47,5.47,0,0,0-1.61,3.83v.14a5.32,5.32,0,0,0,1.62,3.84l.11.11a5.63,5.63,0,0,0,3.84,1.45h.1a2.4,2.4,0,0,1,2.4,2.38h0v10a2.4,2.4,0,0,1-2.4,2.4h-.1a5.7,5.7,0,0,0-3.94,1.55,5.37,5.37,0,0,0-1.64,3.84v.15a5.49,5.49,0,0,0,1.61,3.83,5.32,5.32,0,0,0,3.77,1.58h.28a2.39,2.39,0,0,1,2.41,2.37v0h0v4.78a5.46,5.46,0,0,1-5.45,5.44H5.44A5.46,5.46,0,0,1,0,117.44v-4.78a2.4,2.4,0,0,1,2.4-2.4h.3a5.3,5.3,0,0,0,3.77-1.57,5.55,5.55,0,0,0,1.61-3.83v-.07h0A5.46,5.46,0,0,0,2.6,99.32a2.4,2.4,0,0,1-2.4-2.4v-.16L0,86.92a2.39,2.39,0,0,1,2.34-2.44H2.5a5.67,5.67,0,0,0,4-1.54h0a5.36,5.36,0,0,0,1.62-3.84v-.16a5.37,5.37,0,0,0-1.62-3.83L6.35,75A5.68,5.68,0,0,0,2.5,73.54l-.27,0A2.38,2.38,0,0,1,0,71.15H0V65.53a5.46,5.46,0,0,1,5.44-5.44Zm26.09,45.22a3.74,3.74,0,0,1-1.49,1.46,6.91,6.91,0,0,1-3.15.52c-1.48,0-2.21-.39-2.21-1.17a1.47,1.47,0,0,1,.09-.36l16-28.23a6.19,6.19,0,0,1,.75-1.11,3.53,3.53,0,0,1,1.24-.77,5.87,5.87,0,0,1,2.25-.38c1.87,0,2.8.41,2.8,1.22a.87.87,0,0,1-.09.4L61.28,105.31ZM54,92.45a14.65,14.65,0,0,1-3.46-.36,7.93,7.93,0,0,1-2.72-1.26c-1.72-1.23-2.57-3.62-2.57-7.17s.9-5.77,2.7-7a11,11,0,0,1,6-1.48,11.34,11.34,0,0,1,6.08,1.48c1.81,1.18,2.71,3.49,2.71,7s-.86,6-2.57,7.17A10.75,10.75,0,0,1,54,92.45Zm0-4.37a.72.72,0,0,0,.58-.27c.39-.42.59-1.49.59-3.2A22.78,22.78,0,0,0,55,81.07a2.65,2.65,0,0,0-.41-1.2.78.78,0,0,0-.58-.22c-.79,0-1.18,1.4-1.18,4.21s.39,4.22,1.18,4.22ZM77.7,107.74a14.5,14.5,0,0,1-3.45-.36,7.89,7.89,0,0,1-2.73-1.26C69.8,104.89,69,102.5,69,99s.9-5.76,2.7-6.9a10.76,10.76,0,0,1,6-1.54,11.14,11.14,0,0,1,6.09,1.54q2.7,1.71,2.7,6.9c0,3.58-.85,6-2.57,7.17a10.75,10.75,0,0,1-6.22,1.62Zm0-4.37a.78.78,0,0,0,.58-.23c.4-.45.59-1.53.59-3.24a22.78,22.78,0,0,0-.18-3.54,2.65,2.65,0,0,0-.41-1.2.78.78,0,0,0-.58-.23c-.78,0-1.17,1.41-1.17,4.22s.39,4.22,1.17,4.22Zm29.53-38.48h-78v3.6a1.63,1.63,0,0,1,0,.31A2.1,2.1,0,0,1,25,68.49v-3.6H5.44a.64.64,0,0,0-.45.19.68.68,0,0,0-.19.45V69a10.38,10.38,0,0,1,4.83,2.53l.15.13a10.14,10.14,0,0,1,3.08,7.25v.24a10.14,10.14,0,0,1-3.08,7.24A10.36,10.36,0,0,1,4.84,89L5,94.79a10.26,10.26,0,0,1,7.92,10s0,.1,0,.12a10.28,10.28,0,0,1-8.06,9.93v2.6a.65.65,0,0,0,.64.64H25V114.7a1.45,1.45,0,0,1,0-.3,2.1,2.1,0,0,1,4.18.3v3.38h78a.67.67,0,0,0,.65-.64v-2.61a10.13,10.13,0,0,1-5.07-2.77,10.33,10.33,0,0,1-3-7.15v-.24a10.18,10.18,0,0,1,3.09-7.23h0a10.38,10.38,0,0,1,5-2.66V89a10.27,10.27,0,0,1-4.83-2.52l-.15-.13a10.19,10.19,0,0,1-3.09-7.24v-.25a10.37,10.37,0,0,1,3-7.15A10.14,10.14,0,0,1,107.88,69V65.53a.65.65,0,0,0-.2-.45.6.6,0,0,0-.45-.19ZM25,81.09a2.1,2.1,0,0,0,4.18.31,1.55,1.55,0,0,0,0-.31v-4.2a2.1,2.1,0,0,0-4.18-.3,1.45,1.45,0,0,0,0,.3v4.2ZM25,93.7a2.1,2.1,0,0,0,4.18.3,1.45,1.45,0,0,0,0-.3V89.5a2.1,2.1,0,0,0-4.18-.31,1.55,1.55,0,0,0,0,.31v4.2Zm0,12.6a2.1,2.1,0,0,0,4.18.31,1.63,1.63,0,0,0,0-.31v-4.2a2.1,2.1,0,0,0-4.18-.31,1.63,1.63,0,0,0,0,.31v4.2ZM55.75,43a2.76,2.76,0,0,0,1.08-1.39,2.7,2.7,0,0,0-4-3.13l-4.52,3a2.7,2.7,0,1,0,3,4.52l4.52-3Zm13.56-8.87a2.62,2.62,0,0,0,1.08-1.39,2.7,2.7,0,0,0-4-3.13l-4.53,3A2.76,2.76,0,0,0,60.75,34a2.7,2.7,0,0,0,4,3.13l4.52-3Z" /></svg>
                        <span className="text-sm text-blue-500">Dùng phiếu mua hàng</span>
                      </a>
                    </div>
                  </div>
                </div>
              </div>
              <div className="px-4">
                <div class="bg-[#fff7e2] p-4">
                  <div id="" class="text-center text-[8px] xs:text-[10px] sm:text-xs lg:text-base flex items-center justify-center gap-2">
                    <img src="./images/icon/4518.png" alt="" width={36} className="max-w-[16px] xs:max-w-[20px] lg:max-w-none" />
                    <span> Anh DASSSSS</span> đã chọn hình thức thanh toán <b>tiền mặt khi nhận hàng</b>
                  </div>
                </div>
                <div className="mb-3">
                  <div className="my-4 font-bold text-base sm:text-lg text-center">
                    Anh Dasssss có thể thanh toán trước bằng
                  </div>
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-3">
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-color1">
                            <span className="font-bold"> Tiền mặt khi nhận hàng </span>
                          </div>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-color1">
                            <span className="font-bold"> Cà thẻ khi nhận hàng </span>
                          </div>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="grid items-center cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-color1">
                            <span className="font-bold">Thẻ ATM</span>
                            <img src="./images/icon/atm.png" alt="" width={24} />
                          </div>
                          <span className="text-xs text-color1">(có internet banking)</span>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-color1">
                            <span className="font-bold">Thẻ</span>
                            <img src="./images/icon/2361.png" alt="" width={112} />
                          </div>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-[#ae2070] p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-[#ae2070]">
                            <span className="font-bold">Thanh toán qua</span>
                            <img src="./images/icon/momo.png" alt="" width={36} />
                          </div>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-color1">
                            <span className="font-bold">Thanh toán qua</span>
                            <img src="./images/icon/zalo.png" alt="" width={36} />
                          </div>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-[#ae2070] p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-[#ae2070]">
                            <span className="font-bold">Thanh toán qua</span>
                            <img src="./images/icon/moca.png" alt="" width={36} />
                          </div>
                        </label>
                      </a>
                    </div>
                    <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                      <a className="" href="" title="">
                        <label className="flex items-center gap-3 cursor-pointer">
                          <div className="flex items-center gap-1 text-sm text-color1">
                            <span className="font-bold">Thanh toán qua</span>
                            <img src="./images/icon/vnpay.png" alt="" width={36} />
                          </div>
                        </label>
                      </a>
                    </div>
                  </div>
                  <div className="mb-3 h-[45px] border rounded overflow-hidden border-color1 p-2 flex items-center justify-center cursor-pointer">
                    <a className="" href="" title="">
                      <label className="flex items-center gap-3 cursor-pointer">
                        <div className="flex items-center gap-1 text-sm text-color1">
                          <span className="font-bold">Thanh toán chuyển Khoản</span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chevron-down ml-1" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"></path></svg>
                        </div>
                      </label>
                    </a>
                  </div>
                </div>
              </div>
              <div className="border-t border-[#f4f4f4] px-4 mb-10">
                <div className="flex flex-wrap items-center justify-between gap-3 xs:gap-0">
                  <a className="w-full xs:max-w-[49%] h-[45px] flex items-center justify-center text-sm border border-blue-500 text-blue-500 rounded" href="">
                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-x-lg mr-2" viewBox="0 0 16 16">
                      <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
                    </svg>
                    <span className="text-sm">Hủy đơn hàng</span>
                  </a>
                  <a className="w-full xs:max-w-[49%] h-[45px] flex items-center justify-center text-sm border border-blue-500 rounded" href="">
                    <div className="grid text-center">
                      <span className="text-blue-500 leading-[120%]">Sửa đơn hàng</span>
                      <span className="text-[10px] leading-[100%]">(Thêm/ bớt SP; Đổi địa chỉ/ giờ giao)</span>
                    </div>
                  </a>
                </div>
              </div>
              <div class="mb-4">
                <span class="flex items-center justify-between text-sm">
                  <span className="text-texth">Đánh giá</span>
                  <a class="flex items-center gap-2 text-cltext" href="">
                    <img src="./images/icon/buon.png" alt="" width={20} />Không hài lòng
                  </a>
                  <a class="flex items-center gap-2 text-cltext" href="">
                    <img src="./images/icon/vui.png" alt="" width={20} />Hài lòng
                  </a>
                </span>
              </div>
            </div>
            <div className="w-full bg-white p-4 mb-3 overflow-hidden">
              <div className="flex items-center justify-between mb-3">
                <label className="text-sm"><b>ĐH #64785588</b></label>
                <label class="flex items-center text-sm text-color1">
                  <div className="bg-color1 p-[3px] rounded-full overflow-hidden mr-1">
                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-x-lg text-white" viewBox="0 0 16 16">
                      <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
                    </svg>
                  </div>
                  Hủy giao hàng
                  <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chevron-down ml-4" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                  </svg>
                </label>
              </div>
              <div className="">
                <div className="flex items-center text-sm mb-3">
                  <div className="flex items-center text-sm text-blue-500">
                    Xem thêm
                    <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" fill="currentColor" class="bi bi-chevron-down ml-1" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                    </svg>
                  </div>
                </div>
                <ul className="text-xs mb-5 hidden">
                  <li className="mb-2">
                    <div className="flex items-center gap-1 text-sm text-black">
                      <span className="text-bdtext">Người nhận: </span>
                      <span className="font-medium" id="gender">Anh</span>
                      <span className="font-medium" id="name"> Dasssss</span>
                      <span className="font-medium" id="phone">(0925487121)</span>
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-sm text-black">
                      <span className="text-bdtext">Địa chỉ giao: </span>
                      <span className="font-medium">123, Phường An Khánh (Q2), TP. Thủ Đức (Q2, Q9, Thủ Đức), TP. Hồ Chí Minh</span>
                    </div>
                  </li>
                </ul>
                <ul className="text-xs mb-5">
                  <li className="mb-2">
                    <div className="text-sm text-black">
                      <span className="text-bdtext mr-5">Đã hủy lúc: </span>
                      14:48 29/12
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-sm text-black">
                      Điểm tích luỹ tạm tính: 4.190 điểm (4.190₫)
                    </div>
                  </li>
                  <li className="mb-2">
                    <div className="text-xs text-black">
                      <a className="" href="" title="">Xem hướng dẫn tích và sử dụng điểm</a>
                    </div>
                  </li>
                </ul>
                <div className="zoom-80 xs:zoom-100 border-t mb-3" data-type="">
                  <div className="my-4">
                    <div class="p-2.5 bg-[#e9edf0] rounded text-sm "><b>Đơn hàng #64757572 đã bị hủy lúc 14:48</b> Địa chỉ và sđt không có</div>
                  </div>
                  <div className="text-black">
                    <div className="">
                      <div className="">
                        <div className="border-b py-2">
                          <div className="flex gap-3 justify-between">
                            <div className="flex gap-3">
                              <img alt="Dầu xả Pantene 3MM Biotin ngăn rụng tóc 480ml" src="https://cdn.tgdd.vn/Products/Images/2484/291966/bhx/dau-xa-pantene-3mm-biotin-ngan-rung-toc-480ml-202210110910224605_300x300.jpg" width="60" height="60" />
                              <div className="">
                                <div className="mb-2">
                                  <a className="text-sm" href="">
                                    Dầu xả Pantene 3MM Biotin ngăn rụng tóc 480ml
                                  </a>
                                </div>
                                <div className="text-xs text-blurtext mb-1">
                                  <label>Số lượng:</label>
                                  <span className="text">
                                    1
                                  </span>
                                </div>
                                <div className="text-xs text-blurtext mb-1 flex items-center">
                                  <svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" viewBox="0 0 82.14 122.88" width="14" height="14" fill="currentColor" className="text-blurtext mr-1"><g><path d="M75,80.53c1.09-11.23-0.67-21.99-7.36-34.73c-1.37,8.96-4.51,14.01-11.31,20.53c-2.97-17.65-12.67-34.14-21.9-49.42 c0.54,20.29-6.07,49.28-19.71,64.91c-1.67-8.15-0.47-12.35-1.55-20.57c-1.83,7.34-5.64,11.96-6.69,22.07 c-0.85,8.25,1.47,15.26,5.77,20.64c4.8,6,12.08,10.05,20.23,11.63C56.08,120.16,72.75,103.65,75,80.53L75,80.53z M59.64,117.53 c-4.74,3.09-9.29,4.64-14,5.15c-4.59,0.5-9.23,0.01-14.32-0.97c-9.56-1.85-18.16-6.68-23.91-13.87 c-18.06-22.57,2.36-46.03,3.81-71.92c6.31,7.7,6.95,12.2,8.09,22.31c0.12,1.07,0.22,2.14,0.3,3.21c2.61-6.6,4.57-13.56,5.93-20.43 c2.97-15,3.13-26.27,0.18-41.01c10.94,6.6,16.63,15.28,22.86,26.61c3.84,7,7.52,14.32,10.81,23.37c2.35-9.32,2.9-12.34,0.47-22.3 C88.44,45.72,90.75,97.2,59.64,117.53L59.64,117.53z" /></g></svg>
                                  Giảm 39% chai thứ 2
                                </div>
                              </div>
                            </div>
                            <div className="text-xs">
                              <div className="mb-1">
                                <strong>164.000₫</strong>
                              </div>
                              <div className="line-through text-blurtext">
                                <span><b>186.000₫</b></span>
                              </div>
                            </div>
                          </div>
                          <div className="clr"></div>
                        </div>
                      </div>
                      <div className="border-b-[3px] py-2 text-sm">
                        <div className="flex items-center justify-end mb-2">
                          <span className="text-blurtext">Tiền hàng:</span>
                          <label className="text-cltext w-32 text-right">164.000₫</label>
                        </div>
                        <div className="flex items-center justify-end">
                          <span className="text-blurtext">Phí giao:</span>
                          <label className="text-cltext w-32 text-right">15.000₫</label>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="py-2 text-sm">
                    <div className="flex items-center justify-end mb-2">
                      <span className="text-blurtext">Tiền hàng:</span>
                      <label className="text-cltext w-32 text-right">164.000₫</label>
                    </div>
                    <div className="">
                      <div className="flex items-center justify-end mb-2">
                        <span className="text-blurtext">Phí giao hàng</span>
                        <label className="text-cltext w-32 text-right">
                          15.000₫
                        </label>
                      </div>
                    </div>
                    <div className="">
                      <div className="flex items-center justify-end mb-2">
                        <span className="text-blurtext">Tổng tiền: </span>
                        <label className="text-cltext w-32 text-right">
                          <b>179.000₫</b>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="border-[#f4f4f4] px-4 mb-8">
                <div className="flex flex-wrap items-center justify-center gap-3 xs:gap-0">
                  <a className="w-fit px-3 xs:px-4 h-8 xs:h-[45px] flex items-center justify-center text-sm border border-blue-500 text-blue-500 rounded" href="">
                    <span className="text-xs xs:text-sm">Mua lại đơn hàng này</span>
                  </a>
                </div>
              </div>
              <div class="mb-4">
                <span class="flex items-center justify-between text-sm">
                  <span className="text-texth">Đánh giá</span>
                  <a class="flex items-center gap-2 text-cltext" href="">
                    <img src="./images/icon/buon.png" alt="" width={20} />Không hài lòng
                  </a>
                  <a class="flex items-center gap-2 text-cltext" href="">
                    <img src="./images/icon/vui.png" alt="" width={20} />Hài lòng
                  </a>
                </span>
              </div>
            </div>
          </form>
          <form id="" className="hidden">
            <div className="w-full bg-white mb-3 overflow-hidden">
              <div className="flex items-center justify-between mb-3 py-4 border-b border-gray-200 pb-4 ">
                <label className="text-base px-4">Lịch sử tích lũy điểm</label>
              </div>
              <div className="px-4">
                <table className="w-full">
                  <tbody className="">
                    <tr className="h-16 border-b border-gray-200 last:border-none">
                      <td className="w-[5%]"><span className="font-medium text-base">#</span></td>
                      <td className="w-[24%]"><span className="font-medium text-base">Mã đặt hàng:</span></td>
                      <td className="w-[18%]"><span className="font-medium text-base">Điểm</span></td>
                      <td className="w-[15%]"><span className="font-medium text-base">Chuyển đổi</span></td>
                      <td className="w-[18%]"><span className="font-medium text-base">Ngày</span></td>
                      <td className="w-[20%] text-right"><span className="font-medium text-base">Hoạt động</span></td>
                    </tr>
                    <tr className="h-16 border-b border-gray-200 last:border-none">
                      <td className="w-[5%]"><span className="text-base">1</span></td>
                      <td className="w-[24%]"><span className="text-base">21213132-1231312</span></td>
                      <td className="w-[18%]"><span className="text-base">hoàn lại tiền</span></td>
                      <td className="w-[15%]"><span className="text-xs text-white p-1 rounded bg-blue-500">không</span></td>
                      <td className="w-[22%]"><span className="text-base">22-12-2022</span></td>
                      <td className="w-[20%] text-right"><span className="text-xs p-1 rounded bg-yellow-500">hoàn lại tiền</span></td>
                    </tr>
                    <tr className="h-16 border-b border-gray-200 last:border-none">
                      <td className="w-[5%]"><span className="text-base">2</span></td>
                      <td className="w-[24%]"><span className="text-base">21213132-1231312</span></td>
                      <td className="w-[18%]"><span className="text-base">hoàn lại tiền</span></td>
                      <td className="w-[15%]"><span className="text-xs text-white p-1 rounded bg-blue-500">không</span></td>
                      <td className="w-[22%]"><span className="text-base">22-12-2022</span></td>
                      <td className="w-[20%] text-right"><span className="text-xs p-1 rounded bg-yellow-500">hoàn lại tiền</span></td>
                    </tr>
                    <tr className="h-16 border-b border-gray-200 last:border-none">
                      <td className="w-[5%]"><span className="text-base">3</span></td>
                      <td className="w-[24%]"><span className="text-base">21213132-1231312</span></td>
                      <td className="w-[18%]"><span className="text-base">hoàn lại tiền</span></td>
                      <td className="w-[15%]"><span className="text-xs text-white p-1 rounded bg-blue-500">không</span></td>
                      <td className="w-[22%]"><span className="text-base">22-12-2022</span></td>
                      <td className="w-[20%] text-right"><span className="text-xs p-1 rounded bg-yellow-500">hoàn lại tiền</span></td>
                    </tr>
                    <tr className="h-16 border-b border-gray-200 last:border-none">
                      <td className="w-[5%]"><span className="text-base">4</span></td>
                      <td className="w-[24%]"><span className="text-base">21213132-1231312</span></td>
                      <td className="w-[18%]"><span className="text-base">hoàn lại tiền</span></td>
                      <td className="w-[15%]"><span className="text-xs text-white p-1 rounded bg-blue-500">không</span></td>
                      <td className="w-[22%]"><span className="text-base">22-12-2022</span></td>
                      <td className="w-[20%] text-right"><span className="text-xs p-1 rounded bg-yellow-500">hoàn lại tiền</span></td>
                    </tr>
                    <tr className="h-16 border-b border-gray-200 last:border-none">
                      <td className="w-[5%]"><span className="text-base">5</span></td>
                      <td className="w-[24%]"><span className="text-base">21213132-1231312</span></td>
                      <td className="w-[18%]"><span className="text-base">hoàn lại tiền</span></td>
                      <td className="w-[15%]"><span className="text-xs text-white p-1 rounded bg-blue-500">không</span></td>
                      <td className="w-[22%]"><span className="text-base">22-12-2022</span></td>
                      <td className="w-[20%] text-right"><span className="text-xs p-1 rounded bg-yellow-500">hoàn lại tiền</span></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </form>
        </div>
        <Footer />
      </div>
    </div>
  );
}

