import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Footer from '../../components/footer'
import SlideProduct from '../../components/modules/slide-product';
import SliderRelatedProducts from '../../components/modules/slider-related-products';
import BoxComments from '../../components/modules/box-comments';
import LocationPopup from '../../components/layouts/popup-location';
import Link from 'next/link'

export default function Product(props) {
    var often = []
    for (var i = 0; i < 10; i++) {
        often.push(
            <>
                <a href="" title="" className="border border-red-300 p-1 rounded-md sm:border-0 sm:p-0">
                    <div className="mb-2 flex items-center justify-center w-1/2 m-auto sm:w-full">
                        <img src="../images/sp.png" alt="" className="m-auto" />
                    </div>
                    <div className={`text-gray-600 text-xs sm:text-xs text-center overflow-hidden ${styles.limit_text_2}`}>Thịt heo các loại
                    </div>
                </a>
            </>
        );
    }

    var indents = []
    for (var i = 0; i < 5; i++) {
        indents.push(
            <>
                <a href="" title=""
                    className="flex items-center mb-4 pb-4 border-b border-b-gray-300 last:pb-0 last:border-b-0">
                    <div className="w-2/6 xl:min-w-[65px]">
                        <div className="relative w-full pt-[60%] transition-all">
                            <img src="./images/new.png" alt=""
                                className="absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 w-full h-full object-cover" />
                        </div>
                    </div>
                    <div className={`w-full pl-4  overflow-hidden ${styles.limit_text_2}`}>
                        <p className="text-[13px] text-texth hover:text-color1">Dạy trẻ 5 thói quen sau để phòng
                            bệnh trong mùa tựu trường
                        </p>
                    </div>
                </a>
            </>
        );
    }

    return (
        <div id="main" className="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>Hot products</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <div className="sm:container">
                <div className="lg:pl-60 w-full sm:pt-2">
                    <div className=" bg-white inline-block w-full p-4 mb-4 sm:px-5 sm:mb-5">
                        <div className={`overflow-hidden mb-4 ${styles.limit_text_1}`}>
                            <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Trang chủ</a>
                            <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Sản phẩm</a>
                            <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Hoa quả</a>
                        </div>
                        <div className='grid grid-cols-1 xl:flex gap-y-10 mb-3 sm:mb-8'>
                            <div className='w-full max-w-lg mx-auto xl:w-1/2'>
                                <SlideProduct />
                            </div>
                            <div className='w-full xl:w-1/2 xl:pl-10'>
                                <div className="flex items-center mb-4">
                                    <input className="appearance-none rounded-full h-4 w-4 relative border border-gray-400 bg-white checked:border-red-600 focus:outline-none transition duration-200 align-top bg-no-repeat bg-center bg-contain mr-2 cursor-pointer before:content-[attr(before)] before:absolute before:top-1/2 before:left-1/2 before:-translate-x-1/2 before:-translate-y-1/2 before:w-2 before:h-2 before:rounded-full checked:before:bg-red-600" type="checkbox" name="flexRadioDefault" id="flexRadioDefault1" />
                                    <label className="text-sm cursor-pointer inline-block text-gray-500" htmlFor="flexRadioDefault1">Xem trực tiếp rau củ quả</label>
                                </div>
                                <h2 className='text-xl xs:text-[22px] text-texth font-bold mb-4'>Kiwi vàng Zespri hộp 500g (3-5 trái)</h2>
                                <div className={`p-2 flex items-center justify-between gap-2 mb-5 zoom-80 xs:zoom-100 ${styles.bg_flash_sales}`}>
                                    <div className=''><img src="./images/flast.png" alt="" /></div>
                                    <div className="countdown_time flex items-center gap-1" id="countdown">
                                        <h4 className="text-xs text-white">Kết thúc sau:</h4>
                                        <div id="" className='text-xs text-white flex items-center gap-1'>
                                            <span className='border border-yellow-500 bg-black rounded overflow-hidden px-1 py-[2px]'>23</span>
                                            <span className='border border-yellow-500 bg-black rounded overflow-hidden px-1 py-[2px]'>55</span>
                                            <span className='border border-yellow-500 bg-black rounded overflow-hidden px-1 py-[2px]'>13</span>
                                        </div>
                                    </div>
                                </div>
                                <div className='flex items-center flex-wrap gap-5 mb-3'>
                                    <div className='flex items-end'>
                                        <h3 className='text-xl xs:text-2xl font-bold text-red-500 mr-5'>350.000 ₫</h3>
                                        <p className='text-texth text-xs xs:text-sm'>399.000 ₫</p>
                                    </div>
                                    <div className='bg-red-800 flex items-center justify-center py-[2px] px-1 rounded-sm overflow-hidden'>
                                        <span className='text-[11px] xs:text-xs text-white'>Giảm 25%</span>
                                    </div>
                                </div>
                                <div className='rounded overflow-hidden bg-gray-50 p-1 flex items-center gap-x-3 mb-5'>
                                    <div className='rounded overflow-hidden w-10 h-10'>
                                        <img src="./images/detail3.png" alt='' className='w-full h-full object-cover' />
                                    </div>
                                    <span className='text-sm text-gray-500'>Giảm 20% trái thứ 2</span>
                                </div>
                                <div className='mb-5'>
                                    <h3 className='text-sm text-black mb-2'>12 mã giảm giá</h3>
                                    <div className='mb-5 flex items-center justify-between'>
                                        <div className={`flex items-center overflow-hidden overflow-x-scroll gap-2.5 ${styles.scroll_auto}`}>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                            <div className="px-3 py-[2px] min-w-fit relative z-10 flex items-center justify-center">
                                                <div className='absolute top-0 left-0 w-full h-full -z-10'><img src='./images/subtract.png' alt='' className='w-full h-full' /></div>
                                                <span className='text-[13px] text-blue-600 z-10'>Hoàn 30k xu</span>
                                            </div>
                                        </div>
                                        <button className='ml-2 flex items-center justify-center'>
                                            <svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                                                xmlns="http://www.w3.org/2000/svg" className="ml-1 mt-1">
                                                <path d="M9.09742 12.1336L8.15409 11.1916L11.2208 8.12491L8.15409 5.05824L9.09742 4.12024L13.1041 8.12691L9.09809 12.1336H9.09742ZM5.48075 12.1336L4.53809 11.1916L7.60475 8.12491L4.53809 5.06291L5.48075 4.12024L9.48809 8.12691L5.48142 12.1336H5.48075Z"
                                                    fill="#0052C1" />
                                            </svg>
                                        </button>
                                    </div>

                                    <div className="grid grid-cols-2 gap-4 xs:gap-6">
                                        <div className="p-2 xs:py-3 xs:px-5 border rounded overflow-hidden border-gray-200 grid items-center justify-center hover:border-green-600">
                                            <input className="appearance-none rounded-full h-4 w-4 relative border bg-gray-300 checked:bg-white checked:border-green-600 focus:outline-none transition duration-200 align-top bg-no-repeat bg-center bg-contain mx-auto mb-3 cursor-pointer before:content-[attr(before)] before:absolute before:top-1/2 before:left-1/2 before:-translate-x-1/2 before:-translate-y-1/2 before:w-2 before:h-2 before:rounded-full checked:before:bg-green-600" type="radio" name="flexRadioDefault" id="Default1" />
                                            <label className="text-sm cursor-pointer inline-block text-gray-800" htmlFor="Default1">
                                                <div className='flex items-center gap-x-3'>
                                                    <div className='rounded overflow-hidden w-6 h-6 xs:w-10 xs:h-10'>
                                                        <img src="./images/detail3.png" alt='' className='w-full h-full object-cover' />
                                                    </div>
                                                    <div className=''>
                                                        <h3 className='text-sm text-texth font-medium'>Kg</h3>
                                                        <h3 className='text-sm text-red-500 font-medium'>50.000 ₫</h3>
                                                    </div>
                                                </div>
                                            </label>
                                        </div>
                                        <div className="p-2 xs:py-3 xs:px-5 border rounded overflow-hidden border-gray-200 grid items-center justify-center hover:border-green-600">
                                            <input className="appearance-none rounded-full h-4 w-4 relative border bg-gray-300 checked:bg-white checked:border-green-600 focus:outline-none transition duration-200 align-top bg-no-repeat bg-center bg-contain mx-auto mb-3 cursor-pointer before:content-[attr(before)] before:absolute before:top-1/2 before:left-1/2 before:-translate-x-1/2 before:-translate-y-1/2 before:w-2 before:h-2 before:rounded-full checked:before:bg-green-600" type="radio" name="flexRadioDefault" id="Default2" />
                                            <label className="text-sm cursor-pointer inline-block text-gray-800" htmlFor="Default2">
                                                <div className='flex items-center gap-x-3'>
                                                    <div className='rounded overflow-hidden w-6 h-6 xs:w-10 xs:h-10'>
                                                        <img src="./images/detail3.png" alt='' className='w-full h-full object-cover' />
                                                    </div>
                                                    <div className=''>
                                                        <h3 className='text-sm text-texth font-medium'>Thùng 30 kg</h3>
                                                        <h3 className='text-sm text-red-500 font-medium'>503.000 ₫</h3>
                                                        <p className='text-xs text-texth line-through'>699.000 ₫</p>
                                                    </div>
                                                </div>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <button className="w-full p-3 overflow-hidden bg-color1 border border-color1 text-white leading-[0] rounded flex items-center justify-center mb-7 relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-white before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-color1">
                                    <span className="text-sm xs:text-base font-medium leading-[100%] z-[2] uppercase">Mua ngay</span>
                                </button>
                                <div className=''>
                                    <h2 className='text-lg xs:text-xl text-green-500 mb-3 xs:mb-5 sm:mb-7 uppercase font-medium'>T-mart CAM KẾT!</h2>
                                    <div className="grid grid-cols-1 gap-3 xs:gap-4">
                                        <div className="flex items-start">
                                            <div className="mr-2 mt-1.5 zoom-80 xs:zoom-100">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="text-green-500" viewBox="0 0 16 16">
                                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z" />
                                                </svg>
                                            </div>
                                            <p className="text-texth text-sm xs:text-base">Sản phẩm luôn tươi ngon, chất lượng</p>
                                        </div>
                                        <div className="flex items-start">
                                            <div className="mr-2 mt-1.5 zoom-80 xs:zoom-100">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="text-green-500" viewBox="0 0 16 16">
                                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z" />
                                                </svg>
                                            </div>
                                            <p className="text-texth text-sm xs:text-base">Giao hàng đúng hẹn, đủ hàng</p>
                                        </div>
                                        <div className="flex items-start">
                                            <div className="mr-2 mt-1.5 zoom-80 xs:zoom-100">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="text-green-500" viewBox="0 0 16 16">
                                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z" />
                                                </svg>
                                            </div>
                                            <p className="text-texth text-sm xs:text-base">đổi trả, hoàn tiền dễ dàng</p>
                                        </div>
                                        <div className="flex items-start">
                                            <div className="mr-2 mt-1.5 zoom-80 xs:zoom-100">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="text-green-500" viewBox="0 0 16 16">
                                                    <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z" />
                                                </svg>
                                            </div>
                                            <p className="text-texth text-sm xs:text-base">thân thiện, vui vẻ</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className=" bg-white inline-block w-full p-4 mb-4 sm:p-5 sm:mb-5">
                        <SliderRelatedProducts />
                    </div>
                    <div className=" bg-white inline-block w-full p-4 mb-4 sm:p-5 sm:mb-5">
                        <div className='grid xl:flex gap-10'>
                            <div className='xl:w-3/5'>
                                <div className={`text-texth relative max-h-[460px] border-b border-gray-200 overflow-hidden bg-white ${styles.products_description}`}>
                                    <h2 className='text-xl mb-3 text-black font-medium'>Thông tin sản phẩm</h2>
                                    <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng Đệm lunarlon
                                        mềm và vững chắc Cấu trúc form giày Flywire Công nghệ Flymesh siêu nhẹ và thoáng khí Cấu
                                        trúc lưới nhẹ, đa lớp sử dụng vật liệu lót tối thiểu để giảm độ cứng gót chân</p>
                                    <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                                        thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                                    <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                                        người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>
                                    <p>Đệm lunarlon mềm và vững chắc.</p>
                                    <p>Cấu trúc form giày Flywire.</p>
                                    <p>Công nghệ Flymesh siêu nhẹ và thoáng khí.</p>
                                    <p>Cấu trúc lưới nhẹ, đa lớp sử dụng vật liệu lót tối thiểu để giảm độ
                                        cứng gót chân.</p>
                                    <p>Logo Nike được bố trí nổi bật trên sản phẩm kết hợp màu sắc ấn
                                        tượng, phong cách hiện đại sẽ góp phần khẳng định phong cách thời trang của bạn.
                                    </p>
                                    <p>Nike là nhà cung cấp trang phục và dụng cụ thể thao thương mại công
                                        cộng hàng đầu trên thế giới, có trụ sở tại Hoa Kỳ. Cho đến nay, các sản phẩm của
                                        Nike đang được hàng loạt vận động viên xuất sắc, những người nổi tiếng tin tưởng và
                                        lựa chọn.</p>
                                    <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                                        thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                                    <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                                        người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>
                                    <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                                        thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                                    <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                                        người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>
                                    <p>Đệm lunarlon mềm và vững chắc.</p>
                                    <p>Cấu trúc form giày Flywire.</p>
                                    <p>Công nghệ Flymesh siêu nhẹ và thoáng khí.</p>
                                    <p>Cấu trúc lưới nhẹ, đa lớp sử dụng vật liệu lót tối thiểu để giảm độ
                                        cứng gót chân.</p>
                                    <p>Logo Nike được bố trí nổi bật trên sản phẩm kết hợp màu sắc ấn
                                        tượng, phong cách hiện đại sẽ góp phần khẳng định phong cách thời trang của bạn.
                                    </p>
                                    <p>Nike là nhà cung cấp trang phục và dụng cụ thể thao thương mại công
                                        cộng hàng đầu trên thế giới, có trụ sở tại Hoa Kỳ. Cho đến nay, các sản phẩm của
                                        Nike đang được hàng loạt vận động viên xuất sắc, những người nổi tiếng tin tưởng và
                                        lựa chọn.</p>
                                    <p>Giày Nike Air Zoom Pegasus 36 được sản xuất từ chất liệu vải thể
                                        thao chuyên dụng cùng công nghệ tiên tiến, hỗ trợ tối ưu mọi vận động.</p>
                                    <p>Công nghệ VaporMax mang lại trải nghiệm êm dịu và cân bằng giúp
                                        người mang luôn cảm thấy thoải mái dù phải mang trong thời gian dài.</p>

                                    <div className={`absolute bottom-0 left-0 w-full h-48 flex items-end justify-center pb-4 ${styles.click_more}`}>
                                        <button id="btn-more" className="flex items-center justify-center">
                                            <span className="text-[13px] text-green-500 font-medium">Xem thêm</span>
                                            <svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                                                xmlns="http://www.w3.org/2000/svg" className="ml-1 mt-1">
                                                <path d="M9.09742 12.1336L8.15409 11.1916L11.2208 8.12491L8.15409 5.05824L9.09742 4.12024L13.1041 8.12691L9.09809 12.1336H9.09742ZM5.48075 12.1336L4.53809 11.1916L7.60475 8.12491L4.53809 5.06291L5.48075 4.12024L9.48809 8.12691L5.48142 12.1336H5.48075Z"
                                                    fill="#00A652" />
                                            </svg>
                                        </button>
                                    </div>
                                </div>
                                <div className='flex items-center justify-between flex-wrap xl:flex-nowrap border-b border-gray-200 py-3 mb-5 gap-3'>
                                    <p className='text-sm text-texth'>Bạn có hài lòng với thông tin sản phẩm này không?</p>
                                    <div className='flex items-center gap-x-2'>
                                        <button className='group flex items-center justify-center border border-gray-200 rounded overflow-hidden py-2 px-1 min-w-fit hover:border-blue-500'>
                                            <div className='text-texth mr-2 group-hover:text-blue-500'>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                                                    <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z" />
                                                </svg>
                                            </div>
                                            <span className='text-[13px] text-texth group-hover:text-blue-500'>Hài lòng</span>
                                        </button>
                                        <button className='group flex items-center justify-center border border-gray-200 rounded overflow-hidden py-2 px-1 min-w-fit hover:border-blue-500'>
                                            <div className='text-texth mr-2 group-hover:text-blue-500'>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-hand-thumbs-down" viewBox="0 0 16 16">
                                                    <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z" />
                                                </svg>
                                            </div>
                                            <span className='text-[13px] text-texth group-hover:text-blue-500'>Không hài lòng</span>
                                        </button>
                                    </div>
                                </div>
                                <div className=''>
                                    <div className='border border-gray-200 overflow-hidden rounded mb-7 py-4 px-3 items-center justify-around gap-5 hidden sm:flex'>
                                        <div className=''>
                                            <h1 className='text-black text-center text-2xl sm:text-[40px] font-bold mb-2'>4.5/5</h1>
                                            <div className='max-w-[36px] sm:max-w-[55px] m-auto text-center text-yellow-300 mb-3'>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="" fill="currentColor" className="bi bi-star-fill" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                </svg>
                                            </div>
                                            <p className='text-sm text-texth text-center'>(100 Đánh giá)</p>
                                        </div>
                                        <div className='px-5 border-x border-gray-200'>
                                            <div className="">
                                                <div className="flex items-center mb-2.5">
                                                    <span className="text-sm text-texth mr-1">5</span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-star-fill text-yellow-300" viewBox="0 0 16 16">
                                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                    </svg>
                                                    <div className="relative w-36 h-2 bg-orange-100 rounded-full mx-3 overflow-hidden">
                                                        <div className="bg-yellow-300 w-full h-full rounded-full"></div>
                                                    </div>
                                                    <span className="text-sm text-texth">57</span>
                                                </div>
                                                <div className="flex items-center mb-2.5">
                                                    <span className="text-sm text-texth mr-1">4</span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-star-fill text-yellow-300" viewBox="0 0 16 16">
                                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                    </svg>
                                                    <div className="relative w-36 h-2 bg-orange-100 rounded-full mx-3 overflow-hidden">
                                                        <div className="bg-yellow-300 w-2/3 h-full rounded-full"></div>
                                                    </div>
                                                    <span className="text-sm text-texth">27</span>
                                                </div>
                                                <div className="flex items-center mb-2.5">
                                                    <span className="text-sm text-texth mr-1">3</span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-star-fill text-yellow-300" viewBox="0 0 16 16">
                                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                    </svg>
                                                    <div className="relative w-36 h-2 bg-orange-100 rounded-full mx-3 overflow-hidden">
                                                        <div className="bg-yellow-300 w-1/4 h-full rounded-full"></div>
                                                    </div>
                                                    <span className="text-sm text-texth">15</span>
                                                </div>
                                                <div className="flex items-center mb-2.5">
                                                    <span className="text-sm text-texth mr-1">2</span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-star-fill text-yellow-300" viewBox="0 0 16 16">
                                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                    </svg>
                                                    <div className="relative w-36 h-2 bg-orange-100 rounded-full mx-3 overflow-hidden">
                                                        <div className="bg-yellow-300 w-1/6 h-full rounded-full"></div>
                                                    </div>
                                                    <span className="text-sm text-texth">2</span>
                                                </div>
                                                <div className="flex items-center mb-2.5">
                                                    <span className="text-sm text-texth mr-1">1</span>
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-star-fill text-yellow-300" viewBox="0 0 16 16">
                                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                    </svg>
                                                    <div className="relative w-36 h-2 bg-orange-100 rounded-full mx-3 overflow-hidden">
                                                        <div className="bg-yellow-300 w-0 h-full rounded-full"></div>
                                                    </div>
                                                    <span className="text-sm text-texth">0</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div className=''>
                                            <p className='text-sm text-texth text-center mb-4'>Gửi đánh giá của bạn</p>
                                            <div className='flex items-center justify-center gap-x-1'>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-star-fill text-gray-200 hover:text-yellow-300 cursor-pointer" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-star-fill text-gray-200 hover:text-yellow-300 cursor-pointer" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-star-fill text-gray-200 hover:text-yellow-300 cursor-pointer" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-star-fill text-gray-200 hover:text-yellow-300 cursor-pointer" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" className="bi bi-star-fill text-gray-200 hover:text-yellow-300 cursor-pointer" viewBox="0 0 16 16">
                                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z" />
                                                </svg>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="bg-white">
                                        <BoxComments />
                                    </div>
                                </div>
                            </div>
                            <div className='xl:w-2/5'>
                                <div className='mb-7'>
                                    <div className="mb-4">
                                        <h2 className="font-medium text-black text-base">Nhóm hàng thường mua</h2>
                                    </div>
                                    <div className="grid gap-2 sm:gap-4 grid-cols-5">
                                        {often}
                                    </div>
                                </div>

                                <div className="">
                                    <div className='flex items-center justify-between flex-wrap gap-x-5 mb-4'>
                                        <h2 className="text-base xl:text-sm uppercase text-black font-medium">MẸO HAY TRONG GIA ĐÌNH</h2>
                                        <Link href={'/news'}>
                                            <a href="" title="" className="flex items-center">
                                                <span className="text-[13px] text-green-600">Xem các tin bài khác</span>
                                                <svg width="17" height="17" viewBox="0 0 17 17" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg" className="ml-[2px] mt-[3px]">
                                                    <path
                                                        d="M9.09742 12.1336L8.15409 11.1916L11.2208 8.12491L8.15409 5.05824L9.09742 4.12024L13.1041 8.12691L9.09809 12.1336H9.09742ZM5.48075 12.1336L4.53809 11.1916L7.60475 8.12491L4.53809 5.06291L5.48075 4.12024L9.48809 8.12691L5.48142 12.1336H5.48075Z"
                                                        fill="#00A652" />
                                                </svg>
                                            </a>
                                        </Link>
                                    </div>
                                    <div className="w-full">
                                        <div className="">
                                            {indents}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <Footer />
                </div>
            </div>

            <LocationPopup />
        </div>
    );
}