import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Footer from '../../components/footer'
import SlideProduct from '../../components/modules/slide-product';
import Link from 'next/link'

export default function Product(props) {
    return (
        <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>Hot products</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <div className="container">
                <div className="lg:pl-60 w-full xs:pt-2">
                    <div className=" bg-white inline-block w-full sm:px-5 sm:mb-5">
                        <div class={`overflow-hidden mb-4 mt-4 ${styles.limit_text_1}`}>
                            <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Trang chủ</a>
                            <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Sản phẩm</a>
                            <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Khuyến mãi hot</a>
                        </div>
                        <div className='flex gap-10'>
                            <div className='sm:w-1/2'>
                                <SlideProduct />
                            </div>
                            <div className='sm:w-1/2'>
                                <div class="flex items-center mb-4">
                                    <input class="appearance-none rounded-full h-4 w-4 relative border border-gray-400 bg-white checked:border-red-600 focus:outline-none transition duration-200 align-top bg-no-repeat bg-center bg-contain mr-2 cursor-pointer before:content-[attr(before)] before:absolute before:top-1/2 before:left-1/2 before:-translate-x-1/2 before:-translate-y-1/2 before:w-2 before:h-2 before:rounded-full checked:before:bg-red-600" type="checkbox" name="flexRadioDefault" id="flexRadioDefault1" />
                                    <label class="text-sm cursor-pointer inline-block text-gray-500" for="flexRadioDefault1">Xem trực tiếp rau củ quả</label>
                                </div>
                                <h2 className='text-[22px] text-texth font-bold mb-4'>Kiwi vàng Zespri hộp 500g (3-5 trái)</h2>
                                <div className='flex items-center gap-5'>
                                    <h3 className='text-2xl font-bold text-red-500'>350.000 ₫</h3>
                                    <p className='text-texth text-sm'>399.000 ₫</p>
                                    <div className='bg-red-800 flex items-center justify-center py-[2px] px-[1]'>
                                        <span className='text-xs text-white'>Giảm 25%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <Footer />
                </div>
            </div>
        </div>
    );
}