import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Footer from '../components/footer'
import SlideHome from '../components/modules/slide-home';
import BoxNhomHang from '../components/modules/box-nhom-hang';
import BoxNhomSanPhamKhuyenMai from '../components/modules/box-nhom-san-pham-khuyen-mai';
import BoxNhomSanPham from '../components/modules/box-nhom-san-pham';
import NewsHome from '../components/modules/news-home';
import Link from 'next/link'


export default function Home({}) {
  return (
    <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
      <Head>
        <title>Trang chu</title>
        <meta name="description" content="Generated by Huy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="container">
        <div className="lg:pl-60 w-full pt-2">
          <div className="sm:mb-4">
            <SlideHome />
          </div>
          <div className="w-full p-0 mb-3 lg:p-3 bg-white lg:mb-4">
            <BoxNhomHang/>
          </div>
          <BoxNhomSanPhamKhuyenMai/>
          <BoxNhomSanPham/>
          <BoxNhomSanPham/>
          <BoxNhomSanPham/>
          <NewsHome />
          
          <Footer />
        </div>
      </div>
    </div>
  )
}


// className={`${styles.container}`}