import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Link from "next/link";

export default function Answer({ }) {
    var posts = []
    for (var i = 0; i < 7; i++) {
        posts.push(
            <>
                <div className="w-full bg-white rounded overflow-hidden px-4 mb-5 last:mb-0">
                    <div className="py-4 flex items-center gap-6 sm:gap-8 border-b border-gray-100 relative before:content-[attr(before)] before:absolute before:top-0 before:-left-4 before:w-[2px] before:h-full before:bg-red-500">
                        <div className="w-fit">
                            <h1 className="text-xl sm:text-2xl uppercase font-bold text-red-500">Hỏi</h1>
                        </div>
                        <div className="w-full sm:flex items-center justify-between">
                            <h2 className="text-base sm:text-lg font-medium text-texth mb-3 sm:mb-0">Làm sao để mua hàng với mã khuyến mãi tại T-Mart Online?</h2>
                            <div className="min-w-fit flex sm:grid xl:flex items-center sm:ml-3 before:content-[attr(before)] before:bg-gray-300 before:w-1.5 before:h-1.5 before:rounded-full before:overflow-hidden before:mx-4 before:order-2 sm:before:hidden xl:before:block">
                                <p className="text-xs sm:text-sm text-gray-400 order-1">Nguyễn văn A</p>
                                <p className="text-xs sm:text-sm text-gray-400 order-3">2 ngày trước</p>
                            </div>
                        </div>
                    </div>
                    <div className="py-4 flex items-center gap-6 sm:gap-8 relative before:content-[attr(before)] before:absolute before:top-0 before:-left-4 before:w-[2px] before:h-full before:bg-green-500">
                        <div className="w-fit">
                            <h1 className="text-xl sm:text-2xl uppercase font-bold text-green-500">Đáp</h1>
                        </div>
                        <div className="w-full">
                            <p className="text-sm text-texth">Bạn có mã khuyến mãi tại T-Mart thì làm sao để mua hàng online với mã đó? Xem ngay hướng dẫn bên dưới của T-Mart nhé.
                                Mã khuyến mãi hay voucher tại T-Mart là hình thức giảm giá, ưu đãi dành cho những khách hàng đặc biệt ngẫu nhiên được nhận, và được áp dụng khi mua hàng online. Tham khảo ngay hướng dẫn cách dùng mã khuyến mãi để mua hàng online tại
                                T-Mart.</p>
                        </div>
                    </div>
                </div>
            </>
        );
    }
    return (
        <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>News</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>

            <div className="container">
                <div className="lg:flex lg:gap-6 mb-8">
                    <div className="min-w-[260px] overflow-hidden hidden lg:block">
                        <div className="w-full bg-white border border-gray-300 overflow-hidden p-3 xs:px-6 xs:py-4 h-full">
                            <h3 className="text-lg font-medium text-black mb-5">HỎI ĐÁP THEO CHỦ ĐỀ</h3>
                            <ul className="">
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa1.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Các chủ đề khác</p>
                                </a>
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa2.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Sức khỏe làm đẹp</p>
                                </a>
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa3.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Mẹo vặt đời sống</p>
                                </a>
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa4.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Mẹ và bé</p>
                                </a>
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa5.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Sản phẩm T-Mart</p>
                                </a>
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa6.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Mua hàng, giao hàng</p>
                                </a>
                                <a href="" title="" className="group flex items-center gap-4 mb-4 cursor-pointer">
                                    <div className="">
                                        <img src="../images/icon/qa7.png" alt="" className="" />
                                    </div>
                                    <p className="text-sm text-gray-500 group-hover:text-green-500 leading-[134.69%]">Ăn chơi giải trí</p>
                                </a>
                            </ul>
                        </div>
                    </div>
                    <div className="w-full overflow-hidden mb-5 lg:mb-0">
                        <div className="flex items-center justify-between flex-wrap">
                            <div class={`overflow-hidden my-4 sm:my-5 ${styles.limit_text_1}`}>
                                <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Hỏi đáp</a>
                                <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Mua hàng, giao hàng</a>
                            </div>
                            <div className="hidden sm:block">
                                <a href="" title="" className="group flex items-center">
                                    <div className="mr-3 max-w-[28px]"><img src="../images/icon/user_circle.png" alt="" className="" /></div>
                                    <span className="text-texth text-sm font-medium group-hover:text-red-500">Đăng ký/Đăng nhập</span>
                                </a>
                            </div>
                        </div>
                        <div className="bg-white px-3 py-4 rounded overflow-hidden sm:flex items-center gap-2 mb-7">
                            <div className="w-full mb-3 sm:mb-0">
                                <div className="w-full overflow-hidden px-2 bg-gray-50 h-9 flex items-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 18 18" className="text-gray-400" fill="currentColor">
                                        <path fill-rule="evenodd" clip-rule="evenodd"
                                            d="M17.5893 16.5227L14.5291 13.3863L14.5307 13.3814C15.7032 11.9286 16.3426 10.1122 16.341 8.23907C16.3409 6.61419 15.8644 5.02562 14.9714 3.67313C14.0784 2.32063 12.8089 1.26458 11.3224 0.637769C9.83587 0.0109578 8.19878 -0.158631 6.61697 0.150326C5.03515 0.459284 3.57922 1.23299 2.43225 2.37417C1.28528 3.51535 0.498479 4.97304 0.17078 6.56396C-0.15692 8.15487 -0.0108875 9.80799 0.590514 11.3154C1.19192 12.8229 2.22184 14.1173 3.55077 15.0361C4.87971 15.9548 6.44833 16.4568 8.05939 16.4789C9.93479 16.4833 11.7567 15.8486 13.2294 14.6776L16.2025 17.7637C16.2886 17.8455 16.3905 17.9086 16.5019 17.949C16.6133 17.9893 16.7317 18.006 16.8497 17.9981C16.9678 17.9902 17.083 17.9577 17.188 17.9029C17.2931 17.848 17.3858 17.7719 17.4604 17.6792C18.0901 17.01 17.5893 16.5227 17.5893 16.5227ZM11.5648 13.529C10.5311 14.2437 9.31098 14.6343 8.05778 14.6516C6.36096 14.6633 4.72902 13.9948 3.52088 12.7932C2.31274 11.5915 1.62734 9.95515 1.61542 8.24394C1.61522 6.97999 1.9856 5.7442 2.67998 4.69197C3.37435 3.63974 4.36173 2.81805 5.51793 2.33022C6.67414 1.8424 7.94756 1.71022 9.17806 1.95032C10.4086 2.19041 11.5412 2.79206 12.4335 3.6796C13.3259 4.56713 13.9381 5.70094 14.1932 6.93843C14.4483 8.17592 14.3348 9.46185 13.8672 10.6345C13.3995 11.8072 12.5985 12.8142 11.5648 13.529ZM4.34065 6.77527L5.87092 7.38367L5.87075 7.3841C5.64605 7.94959 5.65513 8.58118 5.896 9.13999C6.13693 9.69894 6.59004 10.1393 7.15564 10.3642L6.54723 11.8944C5.77738 11.5883 5.12886 11.0498 4.68691 10.3617C4.57117 10.1815 4.46961 9.99107 4.38373 9.79184C4.29786 9.59262 4.22913 9.388 4.1776 9.18014C3.98079 8.38635 4.03457 7.54512 4.34065 6.77527Z">
                                        </path>
                                    </svg>
                                    <input type="text" placeholder="Nhập từ khóa tìm kiếm..."
                                        className="w-full h-10 bg-transparent text-gray-500 pl-2 focus:text-black text-[13px] outline-none" />
                                </div>
                            </div>
                            <div className="sm:w-fit flex gap-3 xs:gap-5 items-center">
                                <button className="min-w-[90px] xs:min-w-[120px] h-9 xs:h-10 border border-color1 text-texth leading-[0] rounded flex items-center justify-center relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-color1 before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-white overflow-hidden">
                                    <span className="text-sm z-[2]">Tìm kiếm</span>
                                </button>
                                <span className="text-sm text-texth">Hoặc</span>
                                <button className="w-full sm:w-32 xl:w-40 h-9 xs:h-10 overflow-hidden bg-color1 border border-color1 text-white leading-[0] rounded flex items-center justify-center relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-white before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-color1">
                                    <span className="text-sm leading-[100%] z-[2]">Đặt câu hỏi</span>
                                </button>
                            </div>
                        </div>

                        <div className="">
                            <h2 className="text-xl text-black uppercase font-bold mb-4">CÂU HỎI CHỦ ĐỀ MUA HÀNG, GIAO HÀNG</h2>
                            <div className="">
                                {posts}
                            </div>
                        </div>
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    );
}

