import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import SlideSystem from '../../components/modules/slide-system';
import BoxComments from '../../components/modules/box-comments';
import Link from "next/link";

export default function System({ }) {
    return (
        <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>System</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>
            <div className="sm:container">
                <div className="lg:flex lg:gap-5 sm:pt-5 mb-3">
                    <div className="w-full lg:max-w-3/4 overflow-hidden mb-5 lg:mb-0">
                        <div className="w-full bg-white p-4 sm:p-5 overflow-hidden mb-2.5">
                            <div className="flex items-center justify-between gap-3 flex-wrap mb-5">
                                <h2 className="text-lg text-texth font-medium">Tìm cửa hàng bạn muốn</h2>
                                <a href="" title="" className="flex items-center">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 25" fill="none" className="mr-1">
                                        <path d="M12 21.761C10.7369 20.6837 9.56619 19.5026 8.5 18.23C6.9 16.319 5 13.473 5 10.761C4.99858 7.92858 6.70425 5.37443 9.32107 4.29043C11.9379 3.20644 14.9501 3.80628 16.952 5.81004C18.2685 7.12064 19.0059 8.90343 19 10.761C19 13.473 17.1 16.319 15.5 18.23C14.4338 19.5026 13.2631 20.6837 12 21.761ZM12 5.76104C9.23995 5.76434 7.00331 8.00098 7 10.761C7 11.927 7.527 13.946 10.035 16.947C10.6531 17.6851 11.309 18.3907 12 19.061C12.691 18.3915 13.3472 17.6869 13.966 16.95C16.473 13.945 17 11.926 17 10.761C16.9967 8.00098 14.7601 5.76434 12 5.76104ZM12 13.761C10.3431 13.761 9 12.4179 9 10.761C9 9.10418 10.3431 7.76104 12 7.76104C13.6569 7.76104 15 9.10418 15 10.761C15 11.5567 14.6839 12.3197 14.1213 12.8824C13.5587 13.445 12.7957 13.761 12 13.761Z" fill="#00A652" />
                                    </svg>
                                    <span className="text-sm text-green-600">Xem cửa hàng gần vị trí của bạn</span>
                                </a>
                            </div>
                            <div className="grid grid-cols-1 xs:grid-cols-3 items-center justify-between gap-2.5">
                                <div className="w-full px-2 py-1 sm:px-4 sm:py-3 bg-gray-100 rounded overflow-hidden">
                                    <select name="" id="" class="bg-transparent text-texth focus:text-black text-sm w-full focus:outline-none">
                                        <option value="">Lựa chọn tỉnh thành</option>
                                        <option value="">địa điểm 1</option>
                                        <option value="">địa điểm 2</option>
                                    </select>
                                </div>
                                <div className="w-full px-2 py-1 sm:px-4 sm:py-3 bg-gray-100 rounded overflow-hidden">
                                    <select name="" id="" class="bg-transparent text-texth focus:text-black text-sm w-full focus:outline-none">
                                        <option value="">Quận/huyện</option>
                                        <option value="">địa điểm 1</option>
                                        <option value="">địa điểm 2</option>
                                    </select>
                                </div>
                                <div className="w-full px-2 py-1 sm:px-4 sm:py-3 bg-gray-100 rounded overflow-hidden">
                                    <select name="" id="" class="bg-transparent text-texth focus:text-black text-sm w-full focus:outline-none">
                                        <option value="">Xã/phường</option>
                                        <option value="">địa điểm 1</option>
                                        <option value="">địa điểm 2</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div className="w-full bg-white p-4 sm:p-5 overflow-hidden mb-2.5">
                            <h3 className="text-texth text-sm mb-1">Có <span className="font-bold">100</span> cửa hàng T-Mart</h3>
                            <div className="">
                                <div className="grid grid-cols-1 xs:grid-cols-2 gap-x-8 overflow-hidden mb-5">
                                    <div className="flex items-start py-5 relative before:content-[attr(before)] before:bottom-0 before:left-0 before:w-[200%] before:h-[1px] before:bg-gray-200 before:absolute">
                                        <div class="mr-3 mt-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"></path>
                                            </svg>
                                        </div>
                                        <a href="" title="" className={`text-texth text-sm overflow-hidden ${styles.limit_text_2}`}>Số 6 Biệt thự 2, bán đảo Linh Đàm, P. Hoàng Liệt, Q. Hoàng Mai, Hà Nội</a>
                                    </div>
                                    <div className="flex items-start py-5 relative before:content-[attr(before)] before:bottom-0 before:left-0 before:w-[200%] before:h-[1px] before:bg-gray-200 before:absolute">
                                        <div class="mr-3 mt-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"></path>
                                            </svg>
                                        </div>
                                        <a href="" title="" className={`text-texth text-sm overflow-hidden ${styles.limit_text_2}`}>Số 6 Biệt thự 2, bán đảo Linh Đàm, P. Hoàng Liệt, Q. Hoàng Mai, Hà Nội</a>
                                    </div>
                                    <div className="flex items-start py-5 relative before:content-[attr(before)] before:bottom-0 before:left-0 before:w-[200%] before:h-[1px] before:bg-gray-200 before:absolute">
                                        <div class="mr-3 mt-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"></path>
                                            </svg>
                                        </div>
                                        <a href="" title="" className={`text-texth text-sm overflow-hidden ${styles.limit_text_2}`}>Số 6 Biệt thự 2, bán đảo Linh Đàm, P. Hoàng Liệt, Q. Hoàng Mai, Hà Nội</a>
                                    </div>
                                    <div className="flex items-start py-5 relative before:content-[attr(before)] before:bottom-0 before:left-0 before:w-[200%] before:h-[1px] before:bg-gray-200 before:absolute">
                                        <div class="mr-3 mt-1">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                                                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"></path>
                                            </svg>
                                        </div>
                                        <a href="" title="" className={`text-texth text-sm overflow-hidden ${styles.limit_text_2}`}>Số 6 Biệt thự 2, bán đảo Linh Đàm, P. Hoàng Liệt, Q. Hoàng Mai, Hà Nội</a>
                                    </div>
                                </div>
                                <div class="flex items-center justify-center overflow-hidden">
                                    <a href="" title="" class="flex items-center justify-center">
                                        <span class="text-[13px] mr-2 text-gray-500">Xem thêm 99 cửa hàng</span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" fill="currentColor" class="bi bi-chevron-right transform rotate-90" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"></path></svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div className="w-full bg-white p-4 sm:p-5 overflow-hidden">
                            <h3 className="text-gray-800 text-sm mb-4">Hình ảnh tại cửa hàng</h3>
                            <div className={`${styles.store_image}`}>
                                <SlideSystem />
                            </div>
                        </div>
                    </div>
                    <div className="w-full lg:max-w-1/4 overflow-hidden">
                        <div className="w-full bg-white overflow-hidden mb-2.5 p-4 sm:p-5 ">
                            <div className="grid grid-cols-3 sm:grid-cols-6 lg:grid-cols-2 xl:grid-cols-3 gap-x-3 gap-y-5">
                                <a href="" title="" className="">
                                    <div className="border border-gray-300 rounded overflow-hidden w-full h-28 flex items-center justify-center mb-2.5 p-1">
                                        <img src="./images/Frame.png" alt="" />
                                    </div>
                                    <p className="text-sm text-texth text-center">Giữ xe
                                        miễn phí</p>
                                </a>
                                <a href="" title="" className="">
                                    <div className="border border-gray-300 rounded overflow-hidden w-full h-28 flex items-center justify-center mb-2.5 p-1">
                                        <img src="./images/Frame1.png" alt="" />
                                    </div>
                                    <p className="text-sm text-texth text-center">Nhân viên
                                        nhiệt tình</p>
                                </a>
                                <a href="" title="" className="">
                                    <div className="border border-gray-300 rounded overflow-hidden w-full h-28 flex items-center justify-center mb-2.5 p-1">
                                        <img src="./images/Frame2.png" alt="" />
                                    </div>
                                    <p className="text-sm text-texth text-center">Giá rẻ như
                                        giá chợ</p>
                                </a>
                                <a href="" title="" className="">
                                    <div className="border border-gray-300 rounded overflow-hidden w-full h-28 flex items-center justify-center mb-2.5 p-1">
                                        <img src="./images/Frame3.png" alt="" />
                                    </div>
                                    <p className="text-sm text-texth text-center">Sản phẩm
                                        đa dạng</p>
                                </a>
                                <a href="" title="" className="">
                                    <div className="border border-gray-300 rounded overflow-hidden w-full h-28 flex items-center justify-center mb-2.5 p-1">
                                        <img src="./images/Frame4.png" alt="" />
                                    </div>
                                    <p className="text-sm text-texth text-center">Hàng tươi
                                        mỗi ngày</p>
                                </a>
                                <a href="" title="" className="">
                                    <div className="border border-gray-300 rounded overflow-hidden w-full h-28 flex items-center justify-center mb-2.5 p-1">
                                        <img src="./images/Frame5.png" alt="" />
                                    </div>
                                    <p className="text-sm text-texth text-center">Thanh toán
                                        dễ dàng</p>
                                </a>
                            </div>
                        </div>
                        <div className="w-full bg-white overflow-hidden mb-2.5 py-4 px-3 sm:py-5 ">
                            <h2 className="text-base xl:text-lg text-texth font-medium mb-2.5">Cơ hội làm việc tại T-Mart</h2>
                            <div className="relative transition-all w-full pt-[60%] overflow-hidden rounded">
                                <img src="./images/khuyenmai.png" alt=""
                                    className="absolute top-1/2 left-1/2 overflow-hidden transform -translate-y-1/2 -translate-x-1/2 w-full h-full object-cover" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="sm:container">
                <div className="bg-white p-4 sm:p-5 mb-7">
                    <BoxComments />
                </div>
            </div>
            <div className="container">
                <Footer />
            </div>
        </div>
    );
}

