import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Link from "next/link";

export default function AccountInformation({ }) {
    return (
        <div id="main" className="overflow-hidden bg-gray-100 pb-20 xs:pb-0">

            <Head>
                <title>Tai khoan 2</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>

            <div className="sm:container">
                <div className="w-full max-w-4xl mx-auto mb-8">
                    <div className="my-6">
                        <Link href={'/account'}>
                            <a className="flex items-center" href="" title="">
                                <svg width="21" height="20" viewBox="0 0 21 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M13.9177 4.41083C14.2431 4.73626 14.2431 5.2639 13.9177 5.58934L9.50696 10.0001L13.9177 14.4108C14.2431 14.7363 14.2431 15.2639 13.9177 15.5893C13.5923 15.9148 13.0646 15.9148 12.7392 15.5893L7.73919 10.5893C7.41376 10.2639 7.41376 9.73626 7.73919 9.41083L12.7392 4.41083C13.0646 4.08539 13.5923 4.08539 13.9177 4.41083Z" fill="" className="text-green-600 ml-1" />
                                </svg>
                                <span className="text-green-600 text-[13px]">Quay về lịch sử mua hàng</span>
                            </a>
                        </Link>
                    </div>
                    <div className="w-full bg-white mb-3">
                        <div className="flex items-center p-4 xs:py-6 xs:px-8 border-b border-gray-300">
                            <svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg" className="mr-2">
                                <path d="M12 14.998C14.2091 14.998 16 13.2072 16 10.998C16 8.78891 14.2091 6.99805 12 6.99805C9.79086 6.99805 8 8.78891 8 10.998C8 13.2072 9.79086 14.998 12 14.998ZM12 8.99805C13.1046 8.99805 14 9.89348 14 10.998C14 12.1026 13.1046 12.998 12 12.998C10.8954 12.998 10 12.1026 10 10.998C10 9.89348 10.8954 8.99805 12 8.99805Z" fill="#FF3333" />
                                <path d="M4 22.998C2.89543 22.998 2 22.1026 2 20.998V4.99805C2 3.89348 2.89543 2.99805 4 2.99805H20C21.1046 2.99805 22 3.89348 22 4.99805V20.998C22 22.1026 21.1046 22.998 20 22.998H4ZM4 4.99805V20.998H7C7 18.2366 9.23858 15.998 12 15.998C14.7614 15.998 17 18.2366 17 20.998H20V4.99805H4ZM15 20.998C15 19.3412 13.6569 17.998 12 17.998C10.3431 17.998 9 19.3412 9 20.998H15Z" fill="#FF3333" />
                            </svg>
                            <h2 className="text-base xs:text-lg text-black font-medium">
                                Thông tin cá nhân
                            </h2>
                        </div>
                        <div className="p-4 xs:py-6 xs:px-8">
                            <div className="flex gap-8 sm:gap-12 mb-5">
                                <div className="flex items-center">
                                    <input className="appearance-none rounded-full h-4 w-4 relative border border-gray-400 bg-white checked:border-green-600 focus:outline-none transition duration-200 align-top bg-no-repeat bg-center bg-contain mr-2 cursor-pointer before:content-[attr(before)] before:absolute before:top-1/2 before:left-1/2 before:-translate-x-1/2 before:-translate-y-1/2 before:w-2 before:h-2 before:rounded-full checked:before:bg-green-600" type="radio" name="flexRadioDefault" id="flexRadioDefault1" />
                                    <label className="text-sm cursor-pointer inline-block text-gray-800" for="flexRadioDefault1">
                                        Anh
                                    </label>
                                </div>
                                <div className="flex items-center">
                                    <input className="appearance-none rounded-full h-4 w-4 relative border border-gray-400 bg-white checked:border-green-600 focus:outline-none transition duration-200 align-top bg-no-repeat bg-center bg-contain mr-2 cursor-pointer before:content-[attr(before)] before:absolute before:top-1/2 before:left-1/2 before:-translate-x-1/2 before:-translate-y-1/2 before:w-2 before:h-2 before:rounded-full checked:before:bg-green-600" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked />
                                    <label className="text-sm cursor-pointer inline-block text-gray-800" for="flexRadioDefault2">
                                        Chị
                                    </label>
                                </div>
                            </div>
                            <div className="mb-2">
                                <input type="text"
                                    className="rounded p-3 mb-3 focus:outline-none border border-gray-200 h-auto placeholder-gray-300 text-black text-sm w-full"
                                    placeholder="Họ - tên*" id="typemsg" />
                                <input type="text"
                                    className="rounded p-3 mb-3 focus:outline-none border border-gray-200 h-auto placeholder-gray-300 text-black text-sm w-full"
                                    placeholder="Số điện thoại*" id="typemsg" />
                                <input type="text"
                                    className="rounded p-3 mb-3 focus:outline-none border border-gray-200 h-auto placeholder-gray-300 text-black text-sm w-full"
                                    placeholder="Email (không bắt buộc)" id="typemsg" />
                            </div>
                            <button
                                className="w-full p-3 xs:p-4 overflow-hidden bg-color1 border border-color1 text-white leading-[0] rounded flex items-center justify-center relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-white before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-color1">
                                <span className="text-sm xs:text-base font-medium leading-[100%] z-[2]">
                                    Lưu thông tin chỉnh sửa
                                </span>
                            </button>
                        </div>
                    </div>
                    <div className="w-full bg-white mb-3">
                        <div className="flex items-center p-4 xs:py-6 xs:px-8 border-b border-gray-300">
                            <svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg" className="mr-2">
                                <path d="M12 21.761C10.7369 20.6837 9.56619 19.5026 8.5 18.23C6.9 16.319 5 13.473 5 10.761C4.99858 7.92858 6.70425 5.37443 9.32107 4.29043C11.9379 3.20644 14.9501 3.80628 16.952 5.81004C18.2685 7.12064 19.0059 8.90343 19 10.761C19 13.473 17.1 16.319 15.5 18.23C14.4338 19.5026 13.2631 20.6837 12 21.761ZM12 5.76104C9.23995 5.76434 7.00331 8.00098 7 10.761C7 11.927 7.527 13.946 10.035 16.947C10.6531 17.6851 11.309 18.3907 12 19.061C12.691 18.3915 13.3472 17.6869 13.966 16.95C16.473 13.945 17 11.926 17 10.761C16.9967 8.00098 14.7601 5.76434 12 5.76104ZM12 13.761C10.3431 13.761 9 12.4179 9 10.761C9 9.10418 10.3431 7.76104 12 7.76104C13.6569 7.76104 15 9.10418 15 10.761C15 11.5567 14.6839 12.3197 14.1213 12.8824C13.5587 13.445 12.7957 13.761 12 13.761Z" fill="#FF3333" />
                            </svg>
                            <h2 className="text-base xs:text-lg text-black font-medium">
                                Địa chỉ nhận hàng
                            </h2>
                        </div>
                        <div className="p-4 xs:py-6 xs:px-8">
                            <div className="">
                                <a className="group flex items-center zoom-80 xs:zoom-100" href="" title="">
                                    <svg width="21" height="21" viewBox="0 0 21 21" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className="text-blue-500 mr-2 group-hover:text-red-500">
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M10.1999 2.74674C6.05773 2.74674 2.69987 6.10461 2.69987 10.2467C2.69987 14.3889 6.05773 17.7467 10.1999 17.7467C14.342 17.7467 17.6999 14.3889 17.6999 10.2467C17.6999 6.10461 14.342 2.74674 10.1999 2.74674ZM1.0332 10.2467C1.0332 5.18413 5.13726 1.08008 10.1999 1.08008C15.2625 1.08008 19.3665 5.18413 19.3665 10.2467C19.3665 15.3094 15.2625 19.4134 10.1999 19.4134C5.13726 19.4134 1.0332 15.3094 1.0332 10.2467Z" fill="" />
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M10.2005 6.08008C10.6608 6.08008 11.0339 6.45317 11.0339 6.91341V13.5801C11.0339 14.0403 10.6608 14.4134 10.2005 14.4134C9.74028 14.4134 9.36719 14.0403 9.36719 13.5801V6.91341C9.36719 6.45317 9.74028 6.08008 10.2005 6.08008Z" fill="" />
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M6.0332 10.2469C6.0332 9.78667 6.4063 9.41357 6.86654 9.41357H13.5332C13.9934 9.41357 14.3665 9.78667 14.3665 10.2469C14.3665 10.7071 13.9934 11.0802 13.5332 11.0802H6.86654C6.4063 11.0802 6.0332 10.7071 6.0332 10.2469Z" fill="" />
                                    </svg>
                                    <span className="text-blue-500 group-hover:text-red-500">Thêm địa chỉ nhận hàng </span>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div className="w-full bg-white mb-3">
                        <div className="flex items-center p-4 xs:py-6 xs:px-8 border-b border-gray-300">
                            <svg width="20" height="21" viewBox="0 0 20 21" fill="none" xmlns="http://www.w3.org/2000/svg" className="mr-2">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M4.16699 10.4252C3.70675 10.4252 3.33366 10.7983 3.33366 11.2585V17.0919C3.33366 17.5521 3.70675 17.9252 4.16699 17.9252H15.8337C16.2939 17.9252 16.667 17.5521 16.667 17.0919V11.2585C16.667 10.7983 16.2939 10.4252 15.8337 10.4252H4.16699ZM1.66699 11.2585C1.66699 9.87783 2.78628 8.75854 4.16699 8.75854H15.8337C17.2144 8.75854 18.3337 9.87783 18.3337 11.2585V17.0919C18.3337 18.4726 17.2144 19.5919 15.8337 19.5919H4.16699C2.78628 19.5919 1.66699 18.4726 1.66699 17.0919V11.2585Z" fill="#FF3333" />
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M10 2.92533C9.11594 2.92533 8.2681 3.27652 7.64298 3.90164C7.01786 4.52677 6.66667 5.37461 6.66667 6.25867V9.592C6.66667 10.0522 6.29357 10.4253 5.83333 10.4253C5.3731 10.4253 5 10.0522 5 9.592V6.25867C5 4.93258 5.52678 3.66082 6.46447 2.72313C7.40215 1.78545 8.67392 1.25867 10 1.25867C11.3261 1.25867 12.5979 1.78545 13.5355 2.72313C14.4732 3.66082 15 4.93258 15 6.25867V9.592C15 10.0522 14.6269 10.4253 14.1667 10.4253C13.7064 10.4253 13.3333 10.0522 13.3333 9.592V6.25867C13.3333 5.37461 12.9821 4.52677 12.357 3.90164C11.7319 3.27652 10.8841 2.92533 10 2.92533Z" fill="#FF3333" />
                            </svg>

                            <h2 className="text-base xs:text-lg text-black font-medium">
                                Thay đổi mật khẩu
                            </h2>
                        </div>
                        <div className="p-4 xs:py-6 xs:px-8">
                            <div className="mb-4">
                                <input type="password"
                                    className="rounded p-3 mb-3 focus:outline-none border border-gray-200 h-auto placeholder-gray-300 text-black text-sm w-full"
                                    placeholder="Nhập mật khẩu cũ*" id="typemsg" />
                                <input type="password"
                                    className="rounded p-3 mb-3 focus:outline-none border border-gray-200 h-auto placeholder-gray-300 text-black text-sm w-full"
                                    placeholder="Nhập mật khẩu mới" id="typemsg" />
                                <input type="password"
                                    className="rounded p-3 mb-3 focus:outline-none border border-gray-200 h-auto placeholder-gray-300 text-black text-sm w-full"
                                    placeholder="Nhắc lại mật khẩu mới" id="typemsg" />
                            </div>
                            <button
                                className="w-full mb-2 p-3 xs:p-4 overflow-hidden bg-color1 border border-color1 text-white leading-[0] rounded flex items-center justify-center relative before:duration-500 z-[1] before:content-[attr(before)] before:bg-white before:absolute before:top-0 before:left-0 before:w-full before:h-full before:z-[1] before:origin-center-left before:scale-x-0 hover:before:scale-100 hover:before:duration-500 hover:text-color1">
                                <span className="text-sm xs:text-base font-medium leading-[100%] z-[2]">
                                    Cập nhật mật khẩu
                                </span>
                            </button>
                            <button
                                className="w-full p-3 xs:p-4 overflow-hidden text-black leading-[0] rounded flex items-center justify-center relative hover:text-color1">
                                <span className="text-sm xs:text-base font-medium leading-[100%]">
                                    Thoát tài khoản
                                </span>
                            </button>
                        </div>
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    );
}

