import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import BoxComments from '../../components/modules/box-comments';
import Link from "next/link";

export default function NewsDetail({ }) {
    var posts = []
    for (var i = 0; i < 8; i++) {
        posts.push(
            <>
                <a href="" title="" className="grid gap-3">
                    <div className="w-full">
                        <div className="img relative w-full pt-[70%] transition-all rounded-md overflow-hidden">
                            <img src="./images/image.png" alt=""
                                className="absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 w-full h-full object-cover" />
                        </div>
                    </div>
                    <div className="w-full">
                        <h3 className={`text-xs xs:text-sm leading-[130%] text-black overflow-hidden ${styles.limit_text_2}`}>Biển vô cực Thái Bình có gì mà thu hút giới trẻ check-in cùng học ngay cách làm ốc hương xào củ dừa giòn ngọt đến vậy?</h3>
                    </div>
                </a>
            </>
        );
    }
    return (
        <div id="main" className="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>News detail</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>
            <div className="bg-red-100">
                <div className="container">
                    <ul className="flex items-center justify-between py-3.5 overflow-hidden overflow-x-auto -mx-2">
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="23" viewBox="0 0 22 23" fill="none" className="mr-2 zoom-80 sm:zoom-100">
                                    <path fillRule="evenodd" clipRule="evenodd" d="M10.4374 1.60984C10.7684 1.35238 11.2319 1.35238 11.5629 1.60984L19.8129 8.02651C20.0362 8.20018 20.1668 8.46721 20.1668 8.75008V18.8334C20.1668 19.5628 19.8771 20.2622 19.3614 20.778C18.8457 21.2937 18.1462 21.5834 17.4168 21.5834H4.5835C3.85415 21.5834 3.15468 21.2937 2.63895 20.778C2.12323 20.2622 1.8335 19.5628 1.8335 18.8334V8.75008C1.8335 8.46721 1.9641 8.20018 2.18738 8.02651L10.4374 1.60984ZM3.66683 9.19841V18.8334C3.66683 19.0765 3.76341 19.3097 3.93532 19.4816C4.10722 19.6535 4.34038 19.7501 4.5835 19.7501H17.4168C17.6599 19.7501 17.8931 19.6535 18.065 19.4816C18.2369 19.3097 18.3335 19.0765 18.3335 18.8334V9.19841L11.0002 3.4947L3.66683 9.19841Z" fill="#FF3333" />
                                    <path fillRule="evenodd" clipRule="evenodd" d="M12.5415 12.3461C14.9103 11.0722 17.6768 11.1234 19.4886 11.5261L19.0114 13.6737C17.5232 13.343 15.3397 13.3392 13.5835 14.2837C11.9318 15.1719 10.45 17.0093 10.45 20.8499H8.25C8.25 16.3305 10.0682 13.6762 12.5415 12.3461Z" fill="#FF3333" />
                                </svg>
                                <span className="text-sm sm:text-base text-texth">Trang chủ</span>
                            </a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Món ngon mỗi ngày</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Tư vấn sản phẩm</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Mẹo vặt cuộc sống</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Sống khỏe</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Làm đẹp</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Ăn gì chơi gì</span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div className="container">
                <div className="lg:flex lg:gap-4 pt-4 mb-8">
                    <div className="w-full lg:max-w-3/4 overflow-hidden mb-5 lg:mb-0">
                        <div className="w-full bg-white p-3 xs:py-5 xs:px-5 xl:px-8 rounded overflow-hidden">
                            <div className={`overflow-hidden mb-4 sm:mb-5 ${styles.limit_text_1}`}>
                                <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Kinh nghiệm hay</a>
                                <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Ăn gì chơi gì</a>
                                <a before="" href="" title="" className="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Địa điểm du lịch</a>
                            </div>
                            <div className="text-texth">
                                <h1 className="text-2xl text-green-600 font-medium mb-4">Biển vô cực Thái Bình có gì mà thu hút giới trẻ check-in đến vậy?</h1>
                                <p className="mb-3.5 text-base">Biển vô cực Thái Bình nằm cách thủ đô Hà Nội khoảng 140km, có vẻ đẹp mê hoặc lòng người và hiện đang rất thu hút giới trẻ đến check-in.</p>
                                <div className="bg-blue-50 rounded overflow-hidden p-3 xs:px-5 xs:py-4 sm:px-7 mb-3.5">
                                    <a href="" title="" className="flex items-center">
                                        <span className="text-blue-500 font-medium text-sm xs:text-base">Xem nhanh</span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="15" viewBox="0 0 14 15" fill="none" className="ml-2">
                                            <path fillRule="evenodd" clipRule="evenodd" d="M4.83768 11.4124C4.60988 11.1846 4.60988 10.8152 4.83768 10.5874L7.9252 7.49992L4.83768 4.4124C4.60988 4.18459 4.60988 3.81524 4.83768 3.58744C5.06549 3.35963 5.43483 3.35963 5.66264 3.58744L9.16264 7.08744C9.39045 7.31524 9.39045 7.68459 9.16264 7.9124L5.66264 11.4124C5.43484 11.6402 5.06549 11.6402 4.83768 11.4124Z" fill="#2F80ED" />
                                        </svg>
                                    </a>
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <h3 className="mb-4 text-black text-base font-medium">1. Tìm hiểu về biển vô cực Thái Bình</h3>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <h3 className="mb-4 text-black text-base font-medium">2. Tìm hiểu về biển vô cực Thái Bình</h3>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <h3 className="mb-4 text-black text-base font-medium">3. Tìm hiểu về biển vô cực Thái Bình</h3>
                                <p className="text-green-600 mb-3.5 text-base font-medium">Chụp hình sống ảo</p>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="text-green-600 mb-3.5 text-base font-medium">Tìm hiểu về cuộc sống của ngư dân</p>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                            </div>
                            <div className="bg-blue-50 rounded overflow-hidden p-3 xs:p-5 sm:p-7 mb-5">
                                <h2 className="text-xl text-black font-medium mb-5">Có thể bạn quan tâm</h2>
                                <ul className="list-disc pl-5 text-texth">
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                </ul>
                            </div>
                            <div className="bg-gray-50 rounded overflow-hidden p-4 sm:p-6 mb-6">
                                <h2 className="text-xl text-black font-medium mb-4">Tham khảo thêm</h2>
                                <div className="grid gap-5 grid-cols-2 xs:grid-cols-3 sm:gap-y-8 sm:gap-x-8 xl:gap-x-12 sm:grid-cols-4">
                                    {posts}
                                </div>
                            </div>
                            <div className="">
                                <BoxComments />
                            </div>
                        </div>
                    </div>
                    <div className="w-full lg:max-w-1/4 overflow-hidden">
                        <div className="w-full bg-white rounded overflow-hidden mb-3 p-3 hidden lg:block">
                            <a href="" title="" className="group flex items-center">
                                <div className="mr-3 min-w-[37px]"><img src="../images/icon/user_circle.png" alt="" className="" /></div>
                                <span className="text-texth text-base font-medium group-hover:text-red-500">Đăng ký/Đăng nhập</span>
                            </a>
                        </div>
                        <div className="w-full bg-white rounded overflow-hidden p-3 xs:px-4 xs:py-5 h-full">
                            <div className="flex items-center justify-between mb-4">
                                <h3 className="text-base font-medium text-black">Khuyến mãi</h3>
                                <a href="" title="" className="flex items-center">
                                    <span className="text-[13px] text-green-600">Xem thêm</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="15" viewBox="0 0 14 15" fill="none">
                                        <path fillRule="evenodd" clipRule="evenodd" d="M4.83768 11.4124C4.60988 11.1846 4.60988 10.8152 4.83768 10.5874L7.9252 7.49992L4.83768 4.4124C4.60988 4.18459 4.60988 3.81524 4.83768 3.58744C5.06549 3.35963 5.43483 3.35963 5.66264 3.58744L9.16264 7.08744C9.39045 7.31524 9.39045 7.68459 9.16264 7.9124L5.66264 11.4124C5.43484 11.6402 5.06549 11.6402 4.83768 11.4124Z" fill="#00A652" />
                                    </svg>
                                </a>
                            </div>
                            <div className="mb-4">
                                <div className="w-full mb-4">
                                    <img src="../images/image03.png" alt="" className="w-full" />
                                </div>
                                <div className="">
                                    <p className="font-medium text-black text-base leading-[134.69%]">Từ 9/9 - 15/9/2022, tận hưởng tuần khuyến mãi cực 'sốc' lên đến 40% các mặt hàng </p>
                                </div>
                            </div>
                            <ul className="list-disc pl-6 text-gray-500">
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    );
}

