import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Header from "../../components/header";
import Footer from "../../components/footer";
import Link from "next/link";

export default function NewsDetail({ }) {
    var posts = []
    for (var i = 0; i < 8; i++) {
        posts.push(
            <>
                <a href="" title="" className="grid gap-3">
                    <div className="w-full">
                        <div className="img relative w-full pt-[70%] transition-all rounded-md overflow-hidden">
                            <img src="./images/image.png" alt=""
                                className="absolute top-1/2 left-1/2 transform -translate-y-1/2 -translate-x-1/2 w-full h-full object-cover" />
                        </div>
                    </div>
                    <div className="w-full">
                        <h3 className={`text-xs xs:text-sm leading-[130%] text-black overflow-hidden ${styles.limit_text_2}`}>Biển vô cực Thái Bình có gì mà thu hút giới trẻ check-in cùng học ngay cách làm ốc hương xào củ dừa giòn ngọt đến vậy?</h3>
                    </div>
                </a>
            </>
        );
    }
    return (
        <div id="main" class="overflow-hidden bg-gray-100 pb-20 xs:pb-0">
            <Head>
                <title>News detail</title>
                <meta name="description" content="Generated by Huy" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="overflow-hidden shadow">
                <Header />
            </div>
            <div className="bg-red-100">
                <div className="container">
                    <ul className="flex items-center justify-between py-3.5 overflow-hidden overflow-x-auto -mx-2">
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="23" viewBox="0 0 22 23" fill="none" className="mr-2 zoom-80 sm:zoom-100">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M10.4374 1.60984C10.7684 1.35238 11.2319 1.35238 11.5629 1.60984L19.8129 8.02651C20.0362 8.20018 20.1668 8.46721 20.1668 8.75008V18.8334C20.1668 19.5628 19.8771 20.2622 19.3614 20.778C18.8457 21.2937 18.1462 21.5834 17.4168 21.5834H4.5835C3.85415 21.5834 3.15468 21.2937 2.63895 20.778C2.12323 20.2622 1.8335 19.5628 1.8335 18.8334V8.75008C1.8335 8.46721 1.9641 8.20018 2.18738 8.02651L10.4374 1.60984ZM3.66683 9.19841V18.8334C3.66683 19.0765 3.76341 19.3097 3.93532 19.4816C4.10722 19.6535 4.34038 19.7501 4.5835 19.7501H17.4168C17.6599 19.7501 17.8931 19.6535 18.065 19.4816C18.2369 19.3097 18.3335 19.0765 18.3335 18.8334V9.19841L11.0002 3.4947L3.66683 9.19841Z" fill="#FF3333" />
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M12.5415 12.3461C14.9103 11.0722 17.6768 11.1234 19.4886 11.5261L19.0114 13.6737C17.5232 13.343 15.3397 13.3392 13.5835 14.2837C11.9318 15.1719 10.45 17.0093 10.45 20.8499H8.25C8.25 16.3305 10.0682 13.6762 12.5415 12.3461Z" fill="#FF3333" />
                                </svg>
                                <span className="text-sm sm:text-base text-texth">Trang chủ</span>
                            </a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Món ngon mỗi ngày</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Tư vấn sản phẩm</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Mẹo vặt cuộc sống</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Sống khỏe</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Làm đẹp</span></a>
                        </li>
                        <li className="min-w-fit px-2">
                            <a href="" title="" className="flex items-center"><span className="text-sm sm:text-base text-texth">Ăn gì chơi gì</span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div className="container">
                <div className="lg:flex lg:gap-4 pt-4 mb-8">
                    <div className="w-full lg:max-w-3/4 overflow-hidden mb-5 lg:mb-0">
                        <div className="w-full bg-white p-3 xs:py-5 xs:px-5 xl:px-8 rounded overflow-hidden">
                            <div class={`overflow-hidden mb-4 sm:mb-5 ${styles.limit_text_1}`}>
                                <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Kinh nghiệm hay</a>
                                <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Ăn gì chơi gì</a>
                                <a before="" href="" title="" class="relative text-[13px] text-texth pr-6 before:content-[attr(before)] before:absolute before:top-[8px] before:right-[10px] before:w-1 before:h-1 before:border-t before:border-r before:border-gray-600 before:rotate-45 last:before:content-none last:text-gray-400 last:pr-0">Địa điểm du lịch</a>
                            </div>
                            <div className="text-texth">
                                <h1 className="text-2xl text-green-600 font-medium mb-4">Biển vô cực Thái Bình có gì mà thu hút giới trẻ check-in đến vậy?</h1>
                                <p className="mb-3.5 text-base">Biển vô cực Thái Bình nằm cách thủ đô Hà Nội khoảng 140km, có vẻ đẹp mê hoặc lòng người và hiện đang rất thu hút giới trẻ đến check-in.</p>
                                <div className="bg-blue-50 rounded overflow-hidden p-3 xs:px-5 xs:py-4 sm:px-7 mb-3.5">
                                    <a href="" title="" className="flex items-center">
                                        <span className="text-blue-500 font-medium text-sm xs:text-base">Xem nhanh</span>
                                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="15" viewBox="0 0 14 15" fill="none" className="ml-2">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M4.83768 11.4124C4.60988 11.1846 4.60988 10.8152 4.83768 10.5874L7.9252 7.49992L4.83768 4.4124C4.60988 4.18459 4.60988 3.81524 4.83768 3.58744C5.06549 3.35963 5.43483 3.35963 5.66264 3.58744L9.16264 7.08744C9.39045 7.31524 9.39045 7.68459 9.16264 7.9124L5.66264 11.4124C5.43484 11.6402 5.06549 11.6402 4.83768 11.4124Z" fill="#2F80ED" />
                                        </svg>
                                    </a>
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <h3 className="mb-4 text-black text-base font-medium">1. Tìm hiểu về biển vô cực Thái Bình</h3>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <h3 className="mb-4 text-black text-base font-medium">2. Tìm hiểu về biển vô cực Thái Bình</h3>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <h3 className="mb-4 text-black text-base font-medium">3. Tìm hiểu về biển vô cực Thái Bình</h3>
                                <p className="text-green-600 mb-3.5 text-base font-medium">Chụp hình sống ảo</p>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="text-green-600 mb-3.5 text-base font-medium">Tìm hiểu về cuộc sống của ngư dân</p>
                                <div className="w-full mb-5">
                                    <img src="../images/image.png" alt="" className="w-full" />
                                </div>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                                <p className="mb-3.5 text-base">Tựa như một tấm gương khổng lồ, biển Thái Bình có vẻ đẹp mênh mông, huyền ảo và hiện đang là một trong những địa điểm check-in hot nhất. Hôm nay, hãy cùng với Bách hóa XANH khám phá bãi biển vô cực đặc biệt này nhé!</p>
                            </div>
                            <div className="bg-blue-50 rounded overflow-hidden p-3 xs:p-5 sm:p-7 mb-5">
                                <h2 className="text-xl text-black font-medium mb-5">Có thể bạn quan tâm</h2>
                                <ul className="list-disc pl-5 text-texth">
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                    <li className="mb-2.5 xs:mb-4">
                                        <a href="" title="" className="text-sm xs:text-base text-blue-500">8 điểm du lịch Thái Bình hút khách mà bạn không thể bỏ qua</a>
                                    </li>
                                </ul>
                            </div>
                            <div className="bg-gray-50 rounded overflow-hidden p-4 sm:p-6 mb-6">
                                <h2 className="text-xl text-black font-medium mb-4">Tham khảo thêm</h2>
                                <div className="grid gap-5 grid-cols-2 xs:grid-cols-3 sm:gap-y-8 sm:gap-x-8 xl:gap-x-12 sm:grid-cols-4">
                                    {posts}
                                </div>
                            </div>
                            <div className="">
                                <div className="flex items-center justify-between flex-wrap">
                                    <div className="flex items-center mb-5">
                                        <h3 className="text-texth text-sm font-medium">Hỏi đáp về chương trình</h3>
                                        <a href="" title="" className="text-blue-500 text-sm ml-6">Quy định</a>
                                    </div>
                                    <div className="w-full sm:max-w-[150px] mb-5">
                                        <div className="w-full border border-gray-300 overflow-hidden px-2 bg-white h-9 flex">
                                            <input type="text" placeholder="Tìm theo nội dung"
                                                className="w-full text-gray-300 focus:text-black text-[13px] outline-none" />
                                            <button className="text-gray-300">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 18 18" fill="currentColor">
                                                    <path fill-rule="evenodd" clip-rule="evenodd"
                                                        d="M17.5893 16.5227L14.5291 13.3863L14.5307 13.3814C15.7032 11.9286 16.3426 10.1122 16.341 8.23907C16.3409 6.61419 15.8644 5.02562 14.9714 3.67313C14.0784 2.32063 12.8089 1.26458 11.3224 0.637769C9.83587 0.0109578 8.19878 -0.158631 6.61697 0.150326C5.03515 0.459284 3.57922 1.23299 2.43225 2.37417C1.28528 3.51535 0.498479 4.97304 0.17078 6.56396C-0.15692 8.15487 -0.0108875 9.80799 0.590514 11.3154C1.19192 12.8229 2.22184 14.1173 3.55077 15.0361C4.87971 15.9548 6.44833 16.4568 8.05939 16.4789C9.93479 16.4833 11.7567 15.8486 13.2294 14.6776L16.2025 17.7637C16.2886 17.8455 16.3905 17.9086 16.5019 17.949C16.6133 17.9893 16.7317 18.006 16.8497 17.9981C16.9678 17.9902 17.083 17.9577 17.188 17.9029C17.2931 17.848 17.3858 17.7719 17.4604 17.6792C18.0901 17.01 17.5893 16.5227 17.5893 16.5227ZM11.5648 13.529C10.5311 14.2437 9.31098 14.6343 8.05778 14.6516C6.36096 14.6633 4.72902 13.9948 3.52088 12.7932C2.31274 11.5915 1.62734 9.95515 1.61542 8.24394C1.61522 6.97999 1.9856 5.7442 2.67998 4.69197C3.37435 3.63974 4.36173 2.81805 5.51793 2.33022C6.67414 1.8424 7.94756 1.71022 9.17806 1.95032C10.4086 2.19041 11.5412 2.79206 12.4335 3.6796C13.3259 4.56713 13.9381 5.70094 14.1932 6.93843C14.4483 8.17592 14.3348 9.46185 13.8672 10.6345C13.3995 11.8072 12.5985 12.8142 11.5648 13.529ZM4.34065 6.77527L5.87092 7.38367L5.87075 7.3841C5.64605 7.94959 5.65513 8.58118 5.896 9.13999C6.13693 9.69894 6.59004 10.1393 7.15564 10.3642L6.54723 11.8944C5.77738 11.5883 5.12886 11.0498 4.68691 10.3617C4.57117 10.1815 4.46961 9.99107 4.38373 9.79184C4.29786 9.59262 4.22913 9.388 4.1776 9.18014C3.98079 8.38635 4.03457 7.54512 4.34065 6.77527Z">
                                                    </path>
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div className="mb-5">
                                    <textarea name="" id="" placeholder="Mời bạn bình luận hoặc đặt câu hỏi" className="w-full border border-gray-300 pt-2 pl-2 sm:pt-4 sm:pl-5 text-gray-300 focus:text-black focus:outline-none" rows="5"></textarea>
                                </div>
                                <div className="">
                                    <div className="mb-5">
                                        <div className="flex items-center mb-2">
                                            <h3 className="text-sm text-texth font-medium">Đặng Thư</h3>
                                            <div className="flex items-center ml-3">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 15 14" fill="currentColor" className="text-yellow-300 stroke-yellow-400 ml-[2px]">
                                                    <path d="M7.17829 1.09863L9.12782 5.04816L13.4874 5.68538L10.3329 8.75794L11.0773 13.0986L7.17829 11.0482L3.27924 13.0986L4.02372 8.75794L0.869141 5.68538L5.22876 5.04816L7.17829 1.09863Z" fill="" stroke="" stroke-width="1.03629" stroke-linecap="round" stroke-linejoin="round" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 15 14" fill="currentColor" className="text-yellow-300 stroke-yellow-400 ml-[2px]">
                                                    <path d="M7.17829 1.09863L9.12782 5.04816L13.4874 5.68538L10.3329 8.75794L11.0773 13.0986L7.17829 11.0482L3.27924 13.0986L4.02372 8.75794L0.869141 5.68538L5.22876 5.04816L7.17829 1.09863Z" fill="" stroke="" stroke-width="1.03629" stroke-linecap="round" stroke-linejoin="round" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 15 14" fill="currentColor" className="text-yellow-300 stroke-yellow-400 ml-[2px]">
                                                    <path d="M7.17829 1.09863L9.12782 5.04816L13.4874 5.68538L10.3329 8.75794L11.0773 13.0986L7.17829 11.0482L3.27924 13.0986L4.02372 8.75794L0.869141 5.68538L5.22876 5.04816L7.17829 1.09863Z" fill="" stroke="" stroke-width="1.03629" stroke-linecap="round" stroke-linejoin="round" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 15 14" fill="currentColor" className="text-yellow-300 stroke-yellow-400 ml-[2px]">
                                                    <path d="M7.17829 1.09863L9.12782 5.04816L13.4874 5.68538L10.3329 8.75794L11.0773 13.0986L7.17829 11.0482L3.27924 13.0986L4.02372 8.75794L0.869141 5.68538L5.22876 5.04816L7.17829 1.09863Z" fill="" stroke="" stroke-width="1.03629" stroke-linecap="round" stroke-linejoin="round" />
                                                </svg>
                                                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="14" viewBox="0 0 15 14" fill="currentColor" className="text-gray-300 stroke-gray-300 ml-[2px]">
                                                    <path d="M7.17829 1.09863L9.12782 5.04816L13.4874 5.68538L10.3329 8.75794L11.0773 13.0986L7.17829 11.0482L3.27924 13.0986L4.02372 8.75794L0.869141 5.68538L5.22876 5.04816L7.17829 1.09863Z" fill="" stroke="" stroke-width="1.03629" stroke-linecap="round" stroke-linejoin="round" />
                                                </svg>
                                            </div>
                                            <div className="flex items-center ml-3">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 25 25" fill="none">
                                                    <path d="M9.77471 17.7556L4.82471 12.8057L6.23871 11.3917L9.77621 14.9251L9.77471 14.9267L18.2597 6.44165L19.6737 7.85565L11.1887 16.3417L9.77571 17.7547L9.77471 17.7556Z" fill="#00A652" />
                                                </svg>
                                                <span className="text-sm text-blue-500">Đã mua</span>
                                            </div>
                                        </div>
                                        <div className="text-texth text-sm mb-4">
                                            <p className="">Dưa lưới chứa lượng lớn chất dinh dưỡng có khả năng chống oxy hóa như lutein, zeaxanthin, vitamin C và cryptoxanthin giúp bảo vệ các tế bào...</p>
                                        </div>
                                        <div className="flex flex-wrap gap-5 mb-2">
                                            <img src="./images/detail1.png" alt="" className="w-24 h-24" />
                                            <img src="./images/detail2.png" alt="" className="w-24 h-24" />
                                            <img src="./images/detail3.png" alt="" className="w-24 h-24" />
                                        </div>
                                        <div className="flex items-center gap-7">
                                            <a href="" title="" className="">
                                                <span className="text-blue-500 text-sm ">Thảo luận</span>
                                            </a>
                                            <a href="" title="" className="group flex items-center">
                                                <svg width="17" height="17" viewBox="0 0 17 17" fill="currentColor" xmlns="http://www.w3.org/2000/svg" className="text-gray-400 group-hover:text-blue-500 mr-1">
                                                    <g clip-path="url(#clip0_1_9582)">
                                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M7.51552 1.24108C7.62129 1.0031 7.85729 0.849731 8.11771 0.849731C8.81681 0.849731 9.48728 1.12745 9.98161 1.62178C10.476 2.11612 10.7537 2.78659 10.7537 3.48568V5.46265H13.8212C14.1064 5.46001 14.3888 5.5191 14.649 5.63589C14.9104 5.75324 15.1433 5.92603 15.3313 6.14229C15.5194 6.35855 15.6581 6.61311 15.738 6.88833C15.8179 7.16355 15.8371 7.45286 15.7941 7.7362L14.8847 13.667C14.8846 13.6672 14.8847 13.6668 14.8847 13.667C14.8131 14.1382 14.5736 14.5682 14.2104 14.8769C13.8482 15.1848 13.3871 15.3519 12.9117 15.3475H3.5048C2.98047 15.3475 2.47762 15.1392 2.10687 14.7684C1.73612 14.3977 1.52783 13.8948 1.52783 13.3705V8.75759C1.52783 8.23326 1.73612 7.73042 2.10687 7.35966C2.47762 6.98891 2.98047 6.78062 3.5048 6.78062H5.0535L7.51552 1.24108ZM4.82277 8.0986H3.5048C3.33002 8.0986 3.16241 8.16803 3.03882 8.29161C2.91524 8.4152 2.84581 8.58281 2.84581 8.75759V13.3705C2.84581 13.5453 2.91524 13.7129 3.03882 13.8365C3.16241 13.9601 3.33002 14.0295 3.5048 14.0295H4.82277V8.0986ZM6.14075 14.0295H12.9226C13.0815 14.0313 13.2357 13.9756 13.3568 13.8727C13.4779 13.7698 13.5578 13.6265 13.5816 13.4694L14.491 7.53842C14.491 7.53833 14.491 7.53851 14.491 7.53842C14.5053 7.44405 14.4989 7.34745 14.4723 7.2558C14.4457 7.16405 14.3994 7.0792 14.3368 7.00711C14.2741 6.93503 14.1965 6.87743 14.1093 6.83831C14.0222 6.7992 13.9275 6.7795 13.832 6.78058L13.8246 6.78067L10.0947 6.78062C9.73073 6.78062 9.43569 6.48558 9.43569 6.12164V3.48568C9.43569 3.13613 9.29683 2.8009 9.04966 2.55373C8.89952 2.40359 8.71687 2.29341 8.51827 2.23005L6.14075 7.57946V14.0295Z" fill="" />
                                                    </g>
                                                    <defs>
                                                        <clipPath id="clip0_1_9582">
                                                            <rect width="15.8157" height="15.8157" fill="white" transform="translate(0.869141 0.190796)" />
                                                        </clipPath>
                                                    </defs>
                                                </svg>
                                                <span className="text-gray-400 group-hover:text-blue-500 text-sm ">Thích 200</span>
                                            </a>
                                        </div>
                                    </div>
                                    <div className="p-2 xs:p-4 bg-gray-100 rounded overflow-hidden mb-3">
                                        <div className="flex items-center gap-3 mb-4">
                                            <div className="w-6 h-6 rounded-full overflow-hidden">
                                                <img src="./images/icon/Logo-filnal.png" alt="" className="w-full h-full" />
                                            </div>
                                            <h3 className="text-sm text-texth font-medium">Đặng Thư</h3>
                                            <div className="border border-green-600 px-1 rounded overflow-hidden">
                                                <span className="text-[13px] text-green-600">Quản trị viên</span>
                                            </div>
                                        </div>
                                        <div className="text-texth text-sm">
                                            <p className="">Dưa lưới chứa lượng lớn chất dinh dưỡng có khả năng chống oxy hóa như lutein, zeaxanthin, vitamin C và cryptoxanthin giúp bảo vệ các tế bào...</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="w-full lg:max-w-1/4 overflow-hidden">
                        <div className="w-full bg-white rounded overflow-hidden mb-3 p-3 hidden lg:block">
                            <a href="" title="" className="group flex items-center">
                                <div className="mr-3 min-w-[37px]"><img src="../images/icon/user_circle.png" alt="" className="" /></div>
                                <span className="text-texth text-base font-medium group-hover:text-red-500">Đăng ký/Đăng nhập</span>
                            </a>
                        </div>
                        <div className="w-full bg-white rounded overflow-hidden p-3 xs:px-4 xs:py-5 h-full">
                            <div className="flex items-center justify-between mb-4">
                                <h3 className="text-base font-medium text-black">Khuyến mãi</h3>
                                <a href="" title="" className="flex items-center">
                                    <span className="text-[13px] text-green-600">Xem thêm</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="15" viewBox="0 0 14 15" fill="none">
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M4.83768 11.4124C4.60988 11.1846 4.60988 10.8152 4.83768 10.5874L7.9252 7.49992L4.83768 4.4124C4.60988 4.18459 4.60988 3.81524 4.83768 3.58744C5.06549 3.35963 5.43483 3.35963 5.66264 3.58744L9.16264 7.08744C9.39045 7.31524 9.39045 7.68459 9.16264 7.9124L5.66264 11.4124C5.43484 11.6402 5.06549 11.6402 4.83768 11.4124Z" fill="#00A652" />
                                    </svg>
                                </a>
                            </div>
                            <div className="mb-4">
                                <div className="w-full mb-4">
                                    <img src="../images/image03.png" alt="" className="w-full" />
                                </div>
                                <div className="">
                                    <p className="font-medium text-black text-base leading-[134.69%]">Từ 9/9 - 15/9/2022, tận hưởng tuần khuyến mãi cực 'sốc' lên đến 40% các mặt hàng </p>
                                </div>
                            </div>
                            <ul className="list-disc pl-6 text-gray-500">
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                                <li className="mb-4">
                                    <p className="text-sm text-gray-500 leading-[134.69%]">Từ 01/9 - 30/9/2022, sữa chua ăn mua 1 lốc tặng 1 hộp</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <Footer />
            </div>
        </div>
    );
}

